# generated by scripts/generate_ws_channels.py
# DO NOT EDIT — re-run `make generate-ws` to update

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from cpk_sdk.client.ws_base import _BaseWSConnection

if TYPE_CHECKING:
    from cpk_sdk.client.ws_client import CPKWebSocketClient


# --------------------------------------------------------------------------
# Channel connections
# --------------------------------------------------------------------------


class NotificationsConnection(_BaseWSConnection):
    """Per-user notification stream. Joins a group named `notifications_<user_id>`."""

    CHANNEL = "ws/notifications/"

    async def send_ping(self) -> None:
        """Keep-alive ping"""
        await self.send({"type": "ping"})


class ChatConnection(_BaseWSConnection):
    """Room-based chat. Joins a group named `chat_<room_name>`."""

    CHANNEL = "ws/chat/{room_name}/"

    def __init__(self, client: "CPKWebSocketClient", room_name: str) -> None:
        super().__init__(client, room_name=room_name)

    async def send_chat_message(self, **data: Any) -> None:
        """Receive a message from the room"""
        await self.send({"type": "chat_message", **data})


class LiveFeedConnection(_BaseWSConnection):
    """Real-time order and TTS feed for a restaurant dashboard device."""

    CHANNEL = "ws/restaurants/{restaurant_uuid}/live-feed/"

    def __init__(
        self,
        client: "CPKWebSocketClient",
        restaurant_uuid: str,
        *,
        device_name: str | None = None,
        mode: str | None = None,
        date: str | None = None,
        can_read_messages: str | None = None,
    ) -> None:
        super().__init__(client, restaurant_uuid=restaurant_uuid)
        if device_name is not None:
            self._query_params["device_name"] = device_name
        if mode is not None:
            self._query_params["mode"] = mode
        if date is not None:
            self._query_params["date"] = date
        if can_read_messages is not None:
            self._query_params["can_read_messages"] = can_read_messages

    async def send_ping(self) -> None:
        """Keep-alive"""
        await self.send({"type": "ping"})

    async def send_heartbeat(self, **data: Any) -> None:
        """Device heartbeat — triggers `heartbeat_ack`"""
        await self.send({"type": "heartbeat", **data})


class MapConnection(_BaseWSConnection):
    """Map view — inherits all live-feed events plus driver location updates."""

    CHANNEL = "ws/restaurants/{restaurant_uuid}/map/"

    def __init__(
        self,
        client: "CPKWebSocketClient",
        restaurant_uuid: str,
        *,
        device_name: str | None = None,
        date: str | None = None,
    ) -> None:
        super().__init__(client, restaurant_uuid=restaurant_uuid)
        if device_name is not None:
            self._query_params["device_name"] = device_name
        if date is not None:
            self._query_params["date"] = date

    async def send_ping(self) -> None:
        """Keep-alive"""
        await self.send({"type": "ping"})

    async def send_heartbeat(self, **data: Any) -> None:
        """Device heartbeat"""
        await self.send({"type": "heartbeat", **data})


class PublicTrackerConnection(_BaseWSConnection):
    """Public order tracking — no auth token required. Validates via `tracking_code` query param."""

    CHANNEL = "ws/public-tracker/"
    NO_AUTH = True

    def __init__(
        self,
        client: "CPKWebSocketClient",
        *,
        tracking_code: str,
        username: str | None = None,
    ) -> None:
        super().__init__(client)
        self._query_params["tracking_code"] = tracking_code
        if username is not None:
            self._query_params["username"] = username

    async def send_ping(self) -> None:
        """Keep-alive — also refreshes tracking code TTL"""
        await self.send({"type": "ping"})


class CommanderConnection(_BaseWSConnection):
    """Primary dashboard channel for the Commander frontend. Private tokens only. Joins user, org, and session groups."""

    CHANNEL = "ws/commander/"

    def __init__(
        self,
        client: "CPKWebSocketClient",
        *,
        client_name: str | None = None,
        device_name: str | None = None,
    ) -> None:
        super().__init__(client)
        if client_name is not None:
            self._query_params["client_name"] = client_name
        if device_name is not None:
            self._query_params["device_name"] = device_name

    async def send_ping(self) -> None:
        """Keep-alive — server responds with pong including sequence info"""
        await self.send({"type": "ping"})


# --------------------------------------------------------------------------
# Channels mixin
# --------------------------------------------------------------------------


class _GeneratedChannelsMixin:
    """Mixin that adds channel factory methods to CPKWebSocketClient."""

    def notifications(self) -> "NotificationsConnection":
        """Open the ws/notifications/ channel."""
        return NotificationsConnection(self)  # type: ignore[arg-type]

    def chat(self, room_name: str) -> "ChatConnection":
        """Open the ws/chat/{room_name}/ channel."""
        return ChatConnection(self, room_name)  # type: ignore[arg-type]

    def live_feed(
        self,
        restaurant_uuid: str,
        *,
        device_name: str | None = None,
        mode: str | None = None,
        date: str | None = None,
        can_read_messages: str | None = None,
    ) -> "LiveFeedConnection":
        """Open the ws/restaurants/{restaurant_uuid}/live-feed/ channel."""
        return LiveFeedConnection(
            self,
            restaurant_uuid,
            device_name=device_name,
            mode=mode,
            date=date,
            can_read_messages=can_read_messages,
        )  # type: ignore[arg-type]

    def map(
        self,
        restaurant_uuid: str,
        *,
        device_name: str | None = None,
        date: str | None = None,
    ) -> "MapConnection":
        """Open the ws/restaurants/{restaurant_uuid}/map/ channel."""
        return MapConnection(self, restaurant_uuid, device_name=device_name, date=date)  # type: ignore[arg-type]

    def public_tracker(
        self,
        *,
        tracking_code: str,
        username: str | None = None,
    ) -> "PublicTrackerConnection":
        """Open the ws/public-tracker/ channel."""
        return PublicTrackerConnection(self, tracking_code=tracking_code, username=username)  # type: ignore[arg-type]

    def commander(
        self,
        *,
        client_name: str | None = None,
        device_name: str | None = None,
    ) -> "CommanderConnection":
        """Open the ws/commander/ channel."""
        return CommanderConnection(self, client_name=client_name, device_name=device_name)  # type: ignore[arg-type]
