# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cpk_sdk.client.endpoints.client_deploys import ClientDeploysEndpoints
    from cpk_sdk.client.endpoints.client_errors import ClientErrorsEndpoints
    from cpk_sdk.client.endpoints.deploy_confirmations import DeployConfirmationsEndpoints
    from cpk_sdk.client.endpoints.addresses import AddressesEndpoints
    from cpk_sdk.client.endpoints.auth import AuthEndpoints
    from cpk_sdk.client.endpoints.collectors import CollectorsEndpoints
    from cpk_sdk.client.endpoints.contacts import ContactsEndpoints
    from cpk_sdk.client.endpoints.conversations import ConversationsEndpoints
    from cpk_sdk.client.endpoints.core import CoreEndpoints
    from cpk_sdk.client.endpoints.dashboard import DashboardEndpoints
    from cpk_sdk.client.endpoints.driver_locations import DriverLocationsEndpoints
    from cpk_sdk.client.endpoints.drivers import DriversEndpoints
    from cpk_sdk.client.endpoints.enums import EnumsEndpoints
    from cpk_sdk.client.endpoints.events import EventsEndpoints
    from cpk_sdk.client.endpoints.faqs import FaqsEndpoints
    from cpk_sdk.client.endpoints.forms import FormsEndpoints
    from cpk_sdk.client.endpoints.integrations import IntegrationsEndpoints
    from cpk_sdk.client.endpoints.leads import LeadsEndpoints
    from cpk_sdk.client.endpoints.loyalty_cards import LoyaltyCardsEndpoints
    from cpk_sdk.client.endpoints.messages import MessagesEndpoints
    from cpk_sdk.client.endpoints.operating_cost_categories import OperatingCostCategoriesEndpoints
    from cpk_sdk.client.endpoints.operating_costs import OperatingCostsEndpoints
    from cpk_sdk.client.endpoints.organizations import OrganizationsEndpoints
    from cpk_sdk.client.endpoints.people import PeopleEndpoints
    from cpk_sdk.client.endpoints.pipeline_runs import PipelineRunsEndpoints
    from cpk_sdk.client.endpoints.promotions import PromotionsEndpoints
    from cpk_sdk.client.endpoints.reading_devices import ReadingDevicesEndpoints
    from cpk_sdk.client.endpoints.recipe_menu_items import RecipeMenuItemsEndpoints
    from cpk_sdk.client.endpoints.recipes import RecipesEndpoints
    from cpk_sdk.client.endpoints.restaurants import RestaurantsEndpoints
    from cpk_sdk.client.endpoints.server import ServerEndpoints
    from cpk_sdk.client.endpoints.smart_message_templates import SmartMessageTemplatesEndpoints
    from cpk_sdk.client.endpoints.stickers import StickersEndpoints
    from cpk_sdk.client.endpoints.stock_categories import StockCategoriesEndpoints
    from cpk_sdk.client.endpoints.stock_products import StockProductsEndpoints
    from cpk_sdk.client.endpoints.stock_transactions import StockTransactionsEndpoints
    from cpk_sdk.client.endpoints.stop_addresses import StopAddressesEndpoints
    from cpk_sdk.client.endpoints.stops import StopsEndpoints
    from cpk_sdk.client.endpoints.tables import TablesEndpoints
    from cpk_sdk.client.endpoints.temp_reports import TempReportsEndpoints
    from cpk_sdk.client.endpoints.tickets import TicketsEndpoints
    from cpk_sdk.client.endpoints.tracking_codes import TrackingCodesEndpoints
    from cpk_sdk.client.endpoints.units import UnitsEndpoints
    from cpk_sdk.client.endpoints.untagged import UntaggedEndpoints
    from cpk_sdk.client.endpoints.users import UsersEndpoints
    from cpk_sdk.client.endpoints.vehicles import VehiclesEndpoints
    from cpk_sdk.client.endpoints.vendors import VendorsEndpoints
    from cpk_sdk.client.endpoints.whatsapp_numbers import WhatsappNumbersEndpoints


class _GeneratedEndpointsMixin:
    """Mixin that adds lazy-loaded endpoint namespace properties to the client."""

    def _init_endpoints(self) -> None:
        """Zero-initialise all endpoint cache slots."""
        self._client_deploys: ClientDeploysEndpoints | None = None
        self._client_errors: ClientErrorsEndpoints | None = None
        self._deploy_confirmations: DeployConfirmationsEndpoints | None = None
        self._addresses: AddressesEndpoints | None = None
        self._auth: AuthEndpoints | None = None
        self._collectors: CollectorsEndpoints | None = None
        self._contacts: ContactsEndpoints | None = None
        self._conversations: ConversationsEndpoints | None = None
        self._core: CoreEndpoints | None = None
        self._dashboard: DashboardEndpoints | None = None
        self._driver_locations: DriverLocationsEndpoints | None = None
        self._drivers: DriversEndpoints | None = None
        self._enums: EnumsEndpoints | None = None
        self._events: EventsEndpoints | None = None
        self._faqs: FaqsEndpoints | None = None
        self._forms: FormsEndpoints | None = None
        self._integrations: IntegrationsEndpoints | None = None
        self._leads: LeadsEndpoints | None = None
        self._loyalty_cards: LoyaltyCardsEndpoints | None = None
        self._messages: MessagesEndpoints | None = None
        self._operating_cost_categories: OperatingCostCategoriesEndpoints | None = None
        self._operating_costs: OperatingCostsEndpoints | None = None
        self._organizations: OrganizationsEndpoints | None = None
        self._people: PeopleEndpoints | None = None
        self._pipeline_runs: PipelineRunsEndpoints | None = None
        self._promotions: PromotionsEndpoints | None = None
        self._reading_devices: ReadingDevicesEndpoints | None = None
        self._recipe_menu_items: RecipeMenuItemsEndpoints | None = None
        self._recipes: RecipesEndpoints | None = None
        self._restaurants: RestaurantsEndpoints | None = None
        self._server: ServerEndpoints | None = None
        self._smart_message_templates: SmartMessageTemplatesEndpoints | None = None
        self._stickers: StickersEndpoints | None = None
        self._stock_categories: StockCategoriesEndpoints | None = None
        self._stock_products: StockProductsEndpoints | None = None
        self._stock_transactions: StockTransactionsEndpoints | None = None
        self._stop_addresses: StopAddressesEndpoints | None = None
        self._stops: StopsEndpoints | None = None
        self._tables: TablesEndpoints | None = None
        self._temp_reports: TempReportsEndpoints | None = None
        self._tickets: TicketsEndpoints | None = None
        self._tracking_codes: TrackingCodesEndpoints | None = None
        self._units: UnitsEndpoints | None = None
        self._untagged: UntaggedEndpoints | None = None
        self._users: UsersEndpoints | None = None
        self._vehicles: VehiclesEndpoints | None = None
        self._vendors: VendorsEndpoints | None = None
        self._whatsapp_numbers: WhatsappNumbersEndpoints | None = None

    @property
    def client_deploys(self) -> "ClientDeploysEndpoints":
        if self._client_deploys is None:
            from cpk_sdk.client.endpoints.client_deploys import ClientDeploysEndpoints

            self._client_deploys = ClientDeploysEndpoints(self)
        return self._client_deploys

    @property
    def client_errors(self) -> "ClientErrorsEndpoints":
        if self._client_errors is None:
            from cpk_sdk.client.endpoints.client_errors import ClientErrorsEndpoints

            self._client_errors = ClientErrorsEndpoints(self)
        return self._client_errors

    @property
    def deploy_confirmations(self) -> "DeployConfirmationsEndpoints":
        if self._deploy_confirmations is None:
            from cpk_sdk.client.endpoints.deploy_confirmations import DeployConfirmationsEndpoints

            self._deploy_confirmations = DeployConfirmationsEndpoints(self)
        return self._deploy_confirmations

    @property
    def addresses(self) -> "AddressesEndpoints":
        if self._addresses is None:
            from cpk_sdk.client.endpoints.addresses import AddressesEndpoints

            self._addresses = AddressesEndpoints(self)
        return self._addresses

    @property
    def auth(self) -> "AuthEndpoints":
        if self._auth is None:
            from cpk_sdk.client.endpoints.auth import AuthEndpoints

            self._auth = AuthEndpoints(self)
        return self._auth

    @property
    def collectors(self) -> "CollectorsEndpoints":
        if self._collectors is None:
            from cpk_sdk.client.endpoints.collectors import CollectorsEndpoints

            self._collectors = CollectorsEndpoints(self)
        return self._collectors

    @property
    def contacts(self) -> "ContactsEndpoints":
        if self._contacts is None:
            from cpk_sdk.client.endpoints.contacts import ContactsEndpoints

            self._contacts = ContactsEndpoints(self)
        return self._contacts

    @property
    def conversations(self) -> "ConversationsEndpoints":
        if self._conversations is None:
            from cpk_sdk.client.endpoints.conversations import ConversationsEndpoints

            self._conversations = ConversationsEndpoints(self)
        return self._conversations

    @property
    def core(self) -> "CoreEndpoints":
        if self._core is None:
            from cpk_sdk.client.endpoints.core import CoreEndpoints

            self._core = CoreEndpoints(self)
        return self._core

    @property
    def dashboard(self) -> "DashboardEndpoints":
        if self._dashboard is None:
            from cpk_sdk.client.endpoints.dashboard import DashboardEndpoints

            self._dashboard = DashboardEndpoints(self)
        return self._dashboard

    @property
    def driver_locations(self) -> "DriverLocationsEndpoints":
        if self._driver_locations is None:
            from cpk_sdk.client.endpoints.driver_locations import DriverLocationsEndpoints

            self._driver_locations = DriverLocationsEndpoints(self)
        return self._driver_locations

    @property
    def drivers(self) -> "DriversEndpoints":
        if self._drivers is None:
            from cpk_sdk.client.endpoints.drivers import DriversEndpoints

            self._drivers = DriversEndpoints(self)
        return self._drivers

    @property
    def enums(self) -> "EnumsEndpoints":
        if self._enums is None:
            from cpk_sdk.client.endpoints.enums import EnumsEndpoints

            self._enums = EnumsEndpoints(self)
        return self._enums

    @property
    def events(self) -> "EventsEndpoints":
        if self._events is None:
            from cpk_sdk.client.endpoints.events import EventsEndpoints

            self._events = EventsEndpoints(self)
        return self._events

    @property
    def faqs(self) -> "FaqsEndpoints":
        if self._faqs is None:
            from cpk_sdk.client.endpoints.faqs import FaqsEndpoints

            self._faqs = FaqsEndpoints(self)
        return self._faqs

    @property
    def forms(self) -> "FormsEndpoints":
        if self._forms is None:
            from cpk_sdk.client.endpoints.forms import FormsEndpoints

            self._forms = FormsEndpoints(self)
        return self._forms

    @property
    def integrations(self) -> "IntegrationsEndpoints":
        if self._integrations is None:
            from cpk_sdk.client.endpoints.integrations import IntegrationsEndpoints

            self._integrations = IntegrationsEndpoints(self)
        return self._integrations

    @property
    def leads(self) -> "LeadsEndpoints":
        if self._leads is None:
            from cpk_sdk.client.endpoints.leads import LeadsEndpoints

            self._leads = LeadsEndpoints(self)
        return self._leads

    @property
    def loyalty_cards(self) -> "LoyaltyCardsEndpoints":
        if self._loyalty_cards is None:
            from cpk_sdk.client.endpoints.loyalty_cards import LoyaltyCardsEndpoints

            self._loyalty_cards = LoyaltyCardsEndpoints(self)
        return self._loyalty_cards

    @property
    def messages(self) -> "MessagesEndpoints":
        if self._messages is None:
            from cpk_sdk.client.endpoints.messages import MessagesEndpoints

            self._messages = MessagesEndpoints(self)
        return self._messages

    @property
    def operating_cost_categories(self) -> "OperatingCostCategoriesEndpoints":
        if self._operating_cost_categories is None:
            from cpk_sdk.client.endpoints.operating_cost_categories import (
                OperatingCostCategoriesEndpoints,
            )

            self._operating_cost_categories = OperatingCostCategoriesEndpoints(self)
        return self._operating_cost_categories

    @property
    def operating_costs(self) -> "OperatingCostsEndpoints":
        if self._operating_costs is None:
            from cpk_sdk.client.endpoints.operating_costs import OperatingCostsEndpoints

            self._operating_costs = OperatingCostsEndpoints(self)
        return self._operating_costs

    @property
    def organizations(self) -> "OrganizationsEndpoints":
        if self._organizations is None:
            from cpk_sdk.client.endpoints.organizations import OrganizationsEndpoints

            self._organizations = OrganizationsEndpoints(self)
        return self._organizations

    @property
    def people(self) -> "PeopleEndpoints":
        if self._people is None:
            from cpk_sdk.client.endpoints.people import PeopleEndpoints

            self._people = PeopleEndpoints(self)
        return self._people

    @property
    def pipeline_runs(self) -> "PipelineRunsEndpoints":
        if self._pipeline_runs is None:
            from cpk_sdk.client.endpoints.pipeline_runs import PipelineRunsEndpoints

            self._pipeline_runs = PipelineRunsEndpoints(self)
        return self._pipeline_runs

    @property
    def promotions(self) -> "PromotionsEndpoints":
        if self._promotions is None:
            from cpk_sdk.client.endpoints.promotions import PromotionsEndpoints

            self._promotions = PromotionsEndpoints(self)
        return self._promotions

    @property
    def reading_devices(self) -> "ReadingDevicesEndpoints":
        if self._reading_devices is None:
            from cpk_sdk.client.endpoints.reading_devices import ReadingDevicesEndpoints

            self._reading_devices = ReadingDevicesEndpoints(self)
        return self._reading_devices

    @property
    def recipe_menu_items(self) -> "RecipeMenuItemsEndpoints":
        if self._recipe_menu_items is None:
            from cpk_sdk.client.endpoints.recipe_menu_items import RecipeMenuItemsEndpoints

            self._recipe_menu_items = RecipeMenuItemsEndpoints(self)
        return self._recipe_menu_items

    @property
    def recipes(self) -> "RecipesEndpoints":
        if self._recipes is None:
            from cpk_sdk.client.endpoints.recipes import RecipesEndpoints

            self._recipes = RecipesEndpoints(self)
        return self._recipes

    @property
    def restaurants(self) -> "RestaurantsEndpoints":
        if self._restaurants is None:
            from cpk_sdk.client.endpoints.restaurants import RestaurantsEndpoints

            self._restaurants = RestaurantsEndpoints(self)
        return self._restaurants

    @property
    def server(self) -> "ServerEndpoints":
        if self._server is None:
            from cpk_sdk.client.endpoints.server import ServerEndpoints

            self._server = ServerEndpoints(self)
        return self._server

    @property
    def smart_message_templates(self) -> "SmartMessageTemplatesEndpoints":
        if self._smart_message_templates is None:
            from cpk_sdk.client.endpoints.smart_message_templates import (
                SmartMessageTemplatesEndpoints,
            )

            self._smart_message_templates = SmartMessageTemplatesEndpoints(self)
        return self._smart_message_templates

    @property
    def stickers(self) -> "StickersEndpoints":
        if self._stickers is None:
            from cpk_sdk.client.endpoints.stickers import StickersEndpoints

            self._stickers = StickersEndpoints(self)
        return self._stickers

    @property
    def stock_categories(self) -> "StockCategoriesEndpoints":
        if self._stock_categories is None:
            from cpk_sdk.client.endpoints.stock_categories import StockCategoriesEndpoints

            self._stock_categories = StockCategoriesEndpoints(self)
        return self._stock_categories

    @property
    def stock_products(self) -> "StockProductsEndpoints":
        if self._stock_products is None:
            from cpk_sdk.client.endpoints.stock_products import StockProductsEndpoints

            self._stock_products = StockProductsEndpoints(self)
        return self._stock_products

    @property
    def stock_transactions(self) -> "StockTransactionsEndpoints":
        if self._stock_transactions is None:
            from cpk_sdk.client.endpoints.stock_transactions import StockTransactionsEndpoints

            self._stock_transactions = StockTransactionsEndpoints(self)
        return self._stock_transactions

    @property
    def stop_addresses(self) -> "StopAddressesEndpoints":
        if self._stop_addresses is None:
            from cpk_sdk.client.endpoints.stop_addresses import StopAddressesEndpoints

            self._stop_addresses = StopAddressesEndpoints(self)
        return self._stop_addresses

    @property
    def stops(self) -> "StopsEndpoints":
        if self._stops is None:
            from cpk_sdk.client.endpoints.stops import StopsEndpoints

            self._stops = StopsEndpoints(self)
        return self._stops

    @property
    def tables(self) -> "TablesEndpoints":
        if self._tables is None:
            from cpk_sdk.client.endpoints.tables import TablesEndpoints

            self._tables = TablesEndpoints(self)
        return self._tables

    @property
    def temp_reports(self) -> "TempReportsEndpoints":
        if self._temp_reports is None:
            from cpk_sdk.client.endpoints.temp_reports import TempReportsEndpoints

            self._temp_reports = TempReportsEndpoints(self)
        return self._temp_reports

    @property
    def tickets(self) -> "TicketsEndpoints":
        if self._tickets is None:
            from cpk_sdk.client.endpoints.tickets import TicketsEndpoints

            self._tickets = TicketsEndpoints(self)
        return self._tickets

    @property
    def tracking_codes(self) -> "TrackingCodesEndpoints":
        if self._tracking_codes is None:
            from cpk_sdk.client.endpoints.tracking_codes import TrackingCodesEndpoints

            self._tracking_codes = TrackingCodesEndpoints(self)
        return self._tracking_codes

    @property
    def units(self) -> "UnitsEndpoints":
        if self._units is None:
            from cpk_sdk.client.endpoints.units import UnitsEndpoints

            self._units = UnitsEndpoints(self)
        return self._units

    @property
    def untagged(self) -> "UntaggedEndpoints":
        if self._untagged is None:
            from cpk_sdk.client.endpoints.untagged import UntaggedEndpoints

            self._untagged = UntaggedEndpoints(self)
        return self._untagged

    @property
    def users(self) -> "UsersEndpoints":
        if self._users is None:
            from cpk_sdk.client.endpoints.users import UsersEndpoints

            self._users = UsersEndpoints(self)
        return self._users

    @property
    def vehicles(self) -> "VehiclesEndpoints":
        if self._vehicles is None:
            from cpk_sdk.client.endpoints.vehicles import VehiclesEndpoints

            self._vehicles = VehiclesEndpoints(self)
        return self._vehicles

    @property
    def vendors(self) -> "VendorsEndpoints":
        if self._vendors is None:
            from cpk_sdk.client.endpoints.vendors import VendorsEndpoints

            self._vendors = VendorsEndpoints(self)
        return self._vendors

    @property
    def whatsapp_numbers(self) -> "WhatsappNumbersEndpoints":
        if self._whatsapp_numbers is None:
            from cpk_sdk.client.endpoints.whatsapp_numbers import WhatsappNumbersEndpoints

            self._whatsapp_numbers = WhatsappNumbersEndpoints(self)
        return self._whatsapp_numbers
