# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints


class AddressesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: addresses"""

    async def google_maps_create(self) -> Any:
        """operationId: addresses_google_maps_create"""
        data = await self._client.post("/api/addresses/google-maps/")
        return data
