# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    UserMeResponse,
    UserTokenLoginRequestRequest,
    UserTokenLoginResponse,
)


class AuthEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: auth"""

    async def login_create(self, body: UserTokenLoginRequestRequest) -> UserTokenLoginResponse:
        """operationId: auth_login_create"""
        data = await self._client.post("/api/auth/login/", json=body.model_dump(exclude_none=True))
        return UserTokenLoginResponse.model_validate(data)

    async def me_retrieve(self) -> UserMeResponse:
        """operationId: auth_me_retrieve"""
        data = await self._client.get("/api/auth/me/")
        return UserMeResponse.model_validate(data)
