# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    ClientDeploy,
    ClientDeployRequest,
    PaginatedClientDeployList,
)


class ClientDeploysEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: Client Deploys"""

    async def server_client_deploys_list(
        self,
        *,
        client_type: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedClientDeployList:
        """operationId: server_client_deploys_list"""
        params: dict[str, Any] = {}
        if client_type is not None:
            params["client_type"] = client_type
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/server/client-deploys/", params=params or None)
        return PaginatedClientDeployList.model_validate(data)

    async def server_client_deploys_create(self, body: ClientDeployRequest) -> ClientDeploy:
        """operationId: server_client_deploys_create"""
        data = await self._client.post(
            "/api/server/client-deploys/", json=body.model_dump(exclude_none=True)
        )
        return ClientDeploy.model_validate(data)

    async def server_client_deploys_latest_retrieve(self, app_name: str) -> ClientDeploy:
        """operationId: server_client_deploys_latest_retrieve"""
        data = await self._client.get(f"/api/server/client-deploys/{app_name}/latest/")
        return ClientDeploy.model_validate(data)

    async def server_client_deploys_retrieve(self, uuid: str) -> ClientDeploy:
        """operationId: server_client_deploys_retrieve"""
        data = await self._client.get(f"/api/server/client-deploys/{uuid}/")
        return ClientDeploy.model_validate(data)

    async def server_client_deploys_download_retrieve(self, uuid: str) -> Any:
        """operationId: server_client_deploys_download_retrieve"""
        data = await self._client.get(f"/api/server/client-deploys/{uuid}/download/")
        return data
