# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    ClientError,
    ClientErrorCreateRequest,
    ClientErrorCreateResponse,
    PaginatedClientErrorList,
)


class ClientErrorsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: Client Errors"""

    async def server_client_errors_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedClientErrorList:
        """operationId: server_client_errors_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/server/client-errors/", params=params or None)
        return PaginatedClientErrorList.model_validate(data)

    async def server_client_errors_create(
        self, body: ClientErrorCreateRequest
    ) -> ClientErrorCreateResponse:
        """operationId: server_client_errors_create"""
        data = await self._client.post(
            "/api/server/client-errors/", json=body.model_dump(exclude_none=True)
        )
        return ClientErrorCreateResponse.model_validate(data)

    async def server_client_errors_retrieve(self, uuid: str) -> ClientError:
        """operationId: server_client_errors_retrieve"""
        data = await self._client.get(f"/api/server/client-errors/{uuid}/")
        return ClientError.model_validate(data)
