# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Collector,
    CollectorRequest,
    PaginatedCollectorList,
    PatchedCollectorRequest,
)


class CollectorsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: collectors"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedCollectorList:
        """operationId: collectors_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/collectors/", params=params or None)
        return PaginatedCollectorList.model_validate(data)

    async def create(self, body: CollectorRequest) -> Collector:
        """operationId: collectors_create"""
        data = await self._client.post("/api/collectors/", json=body.model_dump(exclude_none=True))
        return Collector.model_validate(data)

    async def retrieve(self, id: int) -> Collector:
        """operationId: collectors_retrieve"""
        data = await self._client.get(f"/api/collectors/{id}/")
        return Collector.model_validate(data)

    async def update(self, id: int, body: CollectorRequest) -> Collector:
        """operationId: collectors_update"""
        data = await self._client.put(
            f"/api/collectors/{id}/", json=body.model_dump(exclude_none=True)
        )
        return Collector.model_validate(data)

    async def partial_update(self, id: int, body: PatchedCollectorRequest) -> Collector:
        """operationId: collectors_partial_update"""
        data = await self._client.patch(
            f"/api/collectors/{id}/", json=body.model_dump(exclude_none=True)
        )
        return Collector.model_validate(data)

    async def destroy(self, id: int) -> None:
        """operationId: collectors_destroy"""
        await self._client.delete(f"/api/collectors/{id}/")
