# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Contact,
    ContactRequest,
    PaginatedContactList,
    PatchedContactRequest,
)


class ContactsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: contacts"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedContactList:
        """operationId: contacts_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/contacts/", params=params or None)
        return PaginatedContactList.model_validate(data)

    async def create(self, body: ContactRequest) -> Contact:
        """operationId: contacts_create"""
        data = await self._client.post("/api/contacts/", json=body.model_dump(exclude_none=True))
        return Contact.model_validate(data)

    async def retrieve(self, uuid: str) -> Contact:
        """operationId: contacts_retrieve"""
        data = await self._client.get(f"/api/contacts/{uuid}/")
        return Contact.model_validate(data)

    async def update(self, uuid: str, body: ContactRequest) -> Contact:
        """operationId: contacts_update"""
        data = await self._client.put(
            f"/api/contacts/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Contact.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedContactRequest) -> Contact:
        """operationId: contacts_partial_update"""
        data = await self._client.patch(
            f"/api/contacts/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Contact.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: contacts_destroy"""
        await self._client.delete(f"/api/contacts/{uuid}/")
