# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    AddTextMessage,
    AddTextMessageRequest,
    AvailableDocumentRequest,
    Conversation,
    ConversationRequest,
    ConversationRoomAsyncRequestRequest,
    CreateConversationFromLead,
    CreateConversationFromLeadRequest,
    CreateConversationFromUser,
    CreateConversationFromUserRequest,
    CreateSandboxConversation,
    CreateSandboxConversationRequest,
    Message,
    MessageReadStatus,
    MessageReadStatusRequest,
    PaginatedConversationList,
    PaginatedMessageList,
    PaginatedMessageReadStatusList,
    PreviewRefactor,
    PreviewRefactorRequest,
)


class ConversationsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: conversations"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedConversationList:
        """operationId: conversations_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/conversations/", params=params or None)
        return PaginatedConversationList.model_validate(data)

    async def create(self, body: ConversationRequest) -> Conversation:
        """operationId: conversations_create"""
        data = await self._client.post(
            "/api/conversations/", json=body.model_dump(exclude_none=True)
        )
        return Conversation.model_validate(data)

    async def messages_list(
        self,
        conversation_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedMessageList:
        """operationId: conversations_messages_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/conversations/{conversation_uuid}/messages/", params=params or None
        )
        return PaginatedMessageList.model_validate(data)

    async def messages_read_statuses_list(
        self,
        conversation_uuid: str,
        message_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedMessageReadStatusList:
        """operationId: conversations_messages_read_statuses_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/conversations/{conversation_uuid}/messages/{message_uuid}/read-statuses/",
            params=params or None,
        )
        return PaginatedMessageReadStatusList.model_validate(data)

    async def messages_read_statuses_retrieve(
        self,
        conversation_uuid: str,
        message_uuid: str,
        uuid: str,
    ) -> MessageReadStatus:
        """operationId: conversations_messages_read_statuses_retrieve"""
        data = await self._client.get(
            f"/api/conversations/{conversation_uuid}/messages/{message_uuid}/read-statuses/{uuid}/"
        )
        return MessageReadStatus.model_validate(data)

    async def messages_read_statuses_mark_read_create(
        self,
        conversation_uuid: str,
        message_uuid: str,
        body: MessageReadStatusRequest,
    ) -> MessageReadStatus:
        """operationId: conversations_messages_read_statuses_mark_read_create"""
        data = await self._client.post(
            f"/api/conversations/{conversation_uuid}/messages/{message_uuid}/read-statuses/mark_read/",
            json=body.model_dump(exclude_none=True),
        )
        return MessageReadStatus.model_validate(data)

    async def messages_retrieve(self, conversation_uuid: str, uuid: str) -> Message:
        """operationId: conversations_messages_retrieve"""
        data = await self._client.get(f"/api/conversations/{conversation_uuid}/messages/{uuid}/")
        return Message.model_validate(data)

    async def messages_logs_retrieve(self, conversation_uuid: str, uuid: str) -> Message:
        """operationId: conversations_messages_logs_retrieve"""
        data = await self._client.get(
            f"/api/conversations/{conversation_uuid}/messages/{uuid}/logs/"
        )
        return Message.model_validate(data)

    async def messages_text_create(
        self,
        conversation_uuid: str,
        body: AddTextMessageRequest,
    ) -> AddTextMessage:
        """operationId: conversations_messages_text_create"""
        data = await self._client.post(
            f"/api/conversations/{conversation_uuid}/messages/text/",
            json=body.model_dump(exclude_none=True),
        )
        return AddTextMessage.model_validate(data)

    async def retrieve(self, uuid: str) -> Conversation:
        """operationId: conversations_retrieve"""
        data = await self._client.get(f"/api/conversations/{uuid}/")
        return Conversation.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: conversations_destroy"""
        await self._client.delete(f"/api/conversations/{uuid}/")

    async def available_document_create(self, uuid: str, body: AvailableDocumentRequest) -> Message:
        """operationId: conversations_available_document_create"""
        data = await self._client.post(
            f"/api/conversations/{uuid}/available-document/",
            json=body.model_dump(exclude_none=True),
        )
        return Message.model_validate(data)

    async def get_intent_create(self, uuid: str, body: ConversationRequest) -> Conversation:
        """operationId: conversations_get_intent_create"""
        data = await self._client.post(
            f"/api/conversations/{uuid}/get_intent/", json=body.model_dump(exclude_none=True)
        )
        return Conversation.model_validate(data)

    async def refactor_text_create(
        self, uuid: str, body: PreviewRefactorRequest
    ) -> PreviewRefactor:
        """operationId: conversations_refactor_text_create"""
        data = await self._client.post(
            f"/api/conversations/{uuid}/refactor-text/", json=body.model_dump(exclude_none=True)
        )
        return PreviewRefactor.model_validate(data)

    async def toggle_read_create(self, uuid: str, body: ConversationRequest) -> Conversation:
        """operationId: conversations_toggle_read_create"""
        data = await self._client.post(
            f"/api/conversations/{uuid}/toggle-read/", json=body.model_dump(exclude_none=True)
        )
        return Conversation.model_validate(data)

    async def available_documents_list(self, *, ordering: str | None = None) -> Any:
        """operationId: conversations_available_documents_list"""
        params: dict[str, Any] = {}
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            "/api/conversations/available-documents/", params=params or None
        )
        return data

    async def conversation_room_async_create(
        self,
        body: ConversationRoomAsyncRequestRequest,
    ) -> Any:
        """operationId: conversations_conversation_room_async_create"""
        data = await self._client.post(
            "/api/conversations/conversation-room-async/", json=body.model_dump(exclude_none=True)
        )
        return data

    async def from_lead_create(
        self, body: CreateConversationFromLeadRequest
    ) -> CreateConversationFromLead:
        """operationId: conversations_from_lead_create"""
        data = await self._client.post(
            "/api/conversations/from-lead/", json=body.model_dump(exclude_none=True)
        )
        return CreateConversationFromLead.model_validate(data)

    async def from_user_create(
        self, body: CreateConversationFromUserRequest
    ) -> CreateConversationFromUser:
        """operationId: conversations_from_user_create"""
        data = await self._client.post(
            "/api/conversations/from-user/", json=body.model_dump(exclude_none=True)
        )
        return CreateConversationFromUser.model_validate(data)

    async def mine_retrieve(self) -> Conversation:
        """operationId: conversations_mine_retrieve"""
        data = await self._client.get("/api/conversations/mine/")
        return Conversation.model_validate(data)

    async def sandbox_retrieve(self) -> CreateSandboxConversation:
        """operationId: conversations_sandbox_retrieve"""
        data = await self._client.get("/api/conversations/sandbox/")
        return CreateSandboxConversation.model_validate(data)

    async def sandbox_create(
        self, body: CreateSandboxConversationRequest
    ) -> CreateSandboxConversation:
        """operationId: conversations_sandbox_create"""
        data = await self._client.post(
            "/api/conversations/sandbox/", json=body.model_dump(exclude_none=True)
        )
        return CreateSandboxConversation.model_validate(data)
