# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import AboutResponse, VariablesSingletonDefinition


class CoreEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: core"""

    async def about_retrieve(self) -> AboutResponse:
        """operationId: about_retrieve"""
        data = await self._client.get("/api/about/")
        return AboutResponse.model_validate(data)

    async def events_list(
        self,
        *,
        entity_type: str | None = None,
        entity_uuid: str | None = None,
        event_type: str | None = None,
        include_all_organization_events: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        priority: str | None = None,
        restaurant__uuid: str | None = None,
        search: str | None = None,
        sequence: int | None = None,
        sequence__gt: int | None = None,
        sequence__gte: int | None = None,
        sequence__lt: int | None = None,
        sequence__lte: int | None = None,
    ) -> Any:
        """operationId: core_events_list"""
        params: dict[str, Any] = {}
        if entity_type is not None:
            params["entity_type"] = entity_type
        if entity_uuid is not None:
            params["entity_uuid"] = entity_uuid
        if event_type is not None:
            params["event_type"] = event_type
        if include_all_organization_events is not None:
            params["include_all_organization_events"] = include_all_organization_events
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if priority is not None:
            params["priority"] = priority
        if restaurant__uuid is not None:
            params["restaurant__uuid"] = restaurant__uuid
        if search is not None:
            params["search"] = search
        if sequence is not None:
            params["sequence"] = sequence
        if sequence__gt is not None:
            params["sequence__gt"] = sequence__gt
        if sequence__gte is not None:
            params["sequence__gte"] = sequence__gte
        if sequence__lt is not None:
            params["sequence__lt"] = sequence__lt
        if sequence__lte is not None:
            params["sequence__lte"] = sequence__lte
        data = await self._client.get("/api/core/events/", params=params or None)
        return data

    async def events_retrieve(self, uuid: str) -> Any:
        """operationId: core_events_retrieve"""
        data = await self._client.get(f"/api/core/events/{uuid}/")
        return data

    async def events_sample_retrieve(self) -> Any:
        """operationId: core_events_sample_retrieve"""
        data = await self._client.get("/api/core/events/sample/")
        return data

    async def template_variables_retrieve(self) -> VariablesSingletonDefinition:
        """operationId: core_template_variables_retrieve"""
        data = await self._client.get("/api/core/template-variables/")
        return VariablesSingletonDefinition.model_validate(data)
