# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import AppDashboardRequestRequest


class DashboardEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: dashboard"""

    async def init_create(self, body: AppDashboardRequestRequest) -> Any:
        """operationId: dashboard_init_create"""
        data = await self._client.post(
            "/api/dashboard/init/", json=body.model_dump(exclude_none=True)
        )
        return data
