# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    DeployConfirmation,
    DeployConfirmationCreateRequest,
    PaginatedDeployConfirmationList,
)


class DeployConfirmationsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: Deploy Confirmations"""

    async def server_deploy_confirmations_list(
        self,
        *,
        client_deploy: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedDeployConfirmationList:
        """operationId: server_deploy_confirmations_list"""
        params: dict[str, Any] = {}
        if client_deploy is not None:
            params["client_deploy"] = client_deploy
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/server/deploy-confirmations/", params=params or None)
        return PaginatedDeployConfirmationList.model_validate(data)

    async def server_deploy_confirmations_create(
        self,
        body: DeployConfirmationCreateRequest,
    ) -> DeployConfirmation:
        """operationId: server_deploy_confirmations_create"""
        data = await self._client.post(
            "/api/server/deploy-confirmations/", json=body.model_dump(exclude_none=True)
        )
        return DeployConfirmation.model_validate(data)

    async def server_deploy_confirmations_retrieve(self, uuid: str) -> DeployConfirmation:
        """operationId: server_deploy_confirmations_retrieve"""
        data = await self._client.get(f"/api/server/deploy-confirmations/{uuid}/")
        return DeployConfirmation.model_validate(data)

    async def server_deploy_confirmations_destroy(self, uuid: str) -> None:
        """operationId: server_deploy_confirmations_destroy"""
        await self._client.delete(f"/api/server/deploy-confirmations/{uuid}/")
