# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    DriverLocationCreate,
    DriverLocationCreateRequest,
    FullDriverLocation,
    FullDriverLocationRequest,
    PaginatedFullDriverLocationList,
    PatchedFullDriverLocationRequest,
)


class DriverLocationsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: driver-locations"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedFullDriverLocationList:
        """operationId: driver_locations_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/driver-locations/", params=params or None)
        return PaginatedFullDriverLocationList.model_validate(data)

    async def create(self, body: DriverLocationCreateRequest) -> DriverLocationCreate:
        """operationId: driver_locations_create"""
        data = await self._client.post(
            "/api/driver-locations/", json=body.model_dump(exclude_none=True)
        )
        return DriverLocationCreate.model_validate(data)

    async def retrieve(self, uuid: str) -> FullDriverLocation:
        """operationId: driver_locations_retrieve"""
        data = await self._client.get(f"/api/driver-locations/{uuid}/")
        return FullDriverLocation.model_validate(data)

    async def update(self, uuid: str, body: FullDriverLocationRequest) -> FullDriverLocation:
        """operationId: driver_locations_update"""
        data = await self._client.put(
            f"/api/driver-locations/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return FullDriverLocation.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedFullDriverLocationRequest
    ) -> FullDriverLocation:
        """operationId: driver_locations_partial_update"""
        data = await self._client.patch(
            f"/api/driver-locations/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return FullDriverLocation.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: driver_locations_destroy"""
        await self._client.delete(f"/api/driver-locations/{uuid}/")

    async def last_location_retrieve(self) -> FullDriverLocation:
        """operationId: driver_locations_last_location_retrieve"""
        data = await self._client.get("/api/driver-locations/last_location/")
        return FullDriverLocation.model_validate(data)

    async def last_location_retrieve_2(self, tracking_code: str) -> FullDriverLocation:
        """operationId: driver_locations_last_location_retrieve_2"""
        data = await self._client.get(f"/api/driver-locations/last_location/{tracking_code}/")
        return FullDriverLocation.model_validate(data)
