# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Driver,
    DriverCreate,
    DriverCreateRequest,
    DriverRequest,
    PaginatedDriverList,
    PatchedDriverRequest,
)


class DriversEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: drivers"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedDriverList:
        """operationId: drivers_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/drivers/", params=params or None)
        return PaginatedDriverList.model_validate(data)

    async def create(self, body: DriverCreateRequest) -> DriverCreate:
        """operationId: drivers_create"""
        data = await self._client.post("/api/drivers/", json=body.model_dump(exclude_none=True))
        return DriverCreate.model_validate(data)

    async def retrieve(self, uuid: str) -> Driver:
        """operationId: drivers_retrieve"""
        data = await self._client.get(f"/api/drivers/{uuid}/")
        return Driver.model_validate(data)

    async def update(self, uuid: str, body: DriverRequest) -> Driver:
        """operationId: drivers_update"""
        data = await self._client.put(
            f"/api/drivers/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Driver.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedDriverRequest) -> Driver:
        """operationId: drivers_partial_update"""
        data = await self._client.patch(
            f"/api/drivers/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Driver.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: drivers_destroy"""
        await self._client.delete(f"/api/drivers/{uuid}/")

    async def active_route_retrieve(self, uuid: str) -> Driver:
        """operationId: drivers_active_route_retrieve"""
        data = await self._client.get(f"/api/drivers/{uuid}/active_route/")
        return Driver.model_validate(data)
