# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints


class EnumsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: enums"""

    async def retrieve(self) -> Any:
        """operationId: enums_retrieve"""
        data = await self._client.get("/api/enums/")
        return data

    async def retrieve_2(self, name: str) -> Any:
        """operationId: enums_retrieve_2"""
        data = await self._client.get(f"/api/enums/{name}/")
        return data
