# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Event,
    PaginatedEventList,
    PaginatedSlotList,
    PatchedSlotRequest,
    PublicReconfirmationRequest,
    Slot,
    SlotRequest,
)


class EventsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: events"""

    async def list(
        self,
        *,
        collector: str | None = None,
        end_date: str | None = None,
        is_finished: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
        start_date: str | None = None,
        start_date_from: str | None = None,
        start_date_until: str | None = None,
    ) -> PaginatedEventList:
        """operationId: events_list"""
        params: dict[str, Any] = {}
        if collector is not None:
            params["collector"] = collector
        if end_date is not None:
            params["end_date"] = end_date
        if is_finished is not None:
            params["is_finished"] = is_finished
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        if start_date is not None:
            params["start_date"] = start_date
        if start_date_from is not None:
            params["start_date_from"] = start_date_from
        if start_date_until is not None:
            params["start_date_until"] = start_date_until
        data = await self._client.get("/api/events/", params=params or None)
        return PaginatedEventList.model_validate(data)

    async def create(self) -> Event:
        """operationId: events_create"""
        data = await self._client.post("/api/events/")
        return Event.model_validate(data)

    async def slots_list(
        self,
        event_uuid: str,
        *,
        event: str | None = None,
        is_full: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        start_date: str | None = None,
    ) -> PaginatedSlotList:
        """operationId: events_slots_list"""
        params: dict[str, Any] = {}
        if event is not None:
            params["event"] = event
        if is_full is not None:
            params["is_full"] = is_full
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if start_date is not None:
            params["start_date"] = start_date
        data = await self._client.get(f"/api/events/{event_uuid}/slots/", params=params or None)
        return PaginatedSlotList.model_validate(data)

    async def slots_create(self, event_uuid: str, body: SlotRequest) -> Slot:
        """operationId: events_slots_create"""
        data = await self._client.post(
            f"/api/events/{event_uuid}/slots/", json=body.model_dump(exclude_none=True)
        )
        return Slot.model_validate(data)

    async def slots_retrieve(self, event_uuid: str, uuid: str) -> Slot:
        """operationId: events_slots_retrieve"""
        data = await self._client.get(f"/api/events/{event_uuid}/slots/{uuid}/")
        return Slot.model_validate(data)

    async def slots_update(self, event_uuid: str, uuid: str, body: SlotRequest) -> Slot:
        """operationId: events_slots_update"""
        data = await self._client.put(
            f"/api/events/{event_uuid}/slots/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Slot.model_validate(data)

    async def slots_partial_update(
        self,
        event_uuid: str,
        uuid: str,
        body: PatchedSlotRequest,
    ) -> Slot:
        """operationId: events_slots_partial_update"""
        data = await self._client.patch(
            f"/api/events/{event_uuid}/slots/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Slot.model_validate(data)

    async def slots_destroy(self, event_uuid: str, uuid: str) -> None:
        """operationId: events_slots_destroy"""
        await self._client.delete(f"/api/events/{event_uuid}/slots/{uuid}/")

    async def slots_rsvp_create(self, event_uuid: str, uuid: str, body: SlotRequest) -> Slot:
        """operationId: events_slots_rsvp_create"""
        data = await self._client.post(
            f"/api/events/{event_uuid}/slots/{uuid}/rsvp/", json=body.model_dump(exclude_none=True)
        )
        return Slot.model_validate(data)

    async def retrieve(self, uuid: str) -> Event:
        """operationId: events_retrieve"""
        data = await self._client.get(f"/api/events/{uuid}/")
        return Event.model_validate(data)

    async def update(self, uuid: str) -> Event:
        """operationId: events_update"""
        data = await self._client.put(f"/api/events/{uuid}/")
        return Event.model_validate(data)

    async def partial_update(self, uuid: str) -> Event:
        """operationId: events_partial_update"""
        data = await self._client.patch(f"/api/events/{uuid}/")
        return Event.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: events_destroy"""
        await self._client.delete(f"/api/events/{uuid}/")

    async def reconfirmation_create(self, uuid: str, body: PublicReconfirmationRequest) -> Any:
        """operationId: events_reconfirmation_create"""
        data = await self._client.post(
            f"/api/events/{uuid}/reconfirmation/", json=body.model_dump(exclude_none=True)
        )
        return data
