# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import FAQ, FAQRequest, PaginatedFAQList, PatchedFAQRequest


class FaqsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: faqs"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedFAQList:
        """operationId: faqs_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/faqs/", params=params or None)
        return PaginatedFAQList.model_validate(data)

    async def create(self, body: FAQRequest) -> FAQ:
        """operationId: faqs_create"""
        data = await self._client.post("/api/faqs/", json=body.model_dump(exclude_none=True))
        return FAQ.model_validate(data)

    async def retrieve(self, uuid: str) -> FAQ:
        """operationId: faqs_retrieve"""
        data = await self._client.get(f"/api/faqs/{uuid}/")
        return FAQ.model_validate(data)

    async def update(self, uuid: str, body: FAQRequest) -> FAQ:
        """operationId: faqs_update"""
        data = await self._client.put(f"/api/faqs/{uuid}/", json=body.model_dump(exclude_none=True))
        return FAQ.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedFAQRequest) -> FAQ:
        """operationId: faqs_partial_update"""
        data = await self._client.patch(
            f"/api/faqs/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return FAQ.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: faqs_destroy"""
        await self._client.delete(f"/api/faqs/{uuid}/")
