# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedQuestionList,
    PatchedQuestionRequest,
    Question,
    QuestionRequest,
    QuestionSerializerWithOptions,
)


class FormsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: forms"""

    async def questions_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedQuestionList:
        """operationId: forms_questions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/forms/questions/", params=params or None)
        return PaginatedQuestionList.model_validate(data)

    async def questions_create(self, body: QuestionRequest) -> Question:
        """operationId: forms_questions_create"""
        data = await self._client.post(
            "/api/forms/questions/", json=body.model_dump(exclude_none=True)
        )
        return Question.model_validate(data)

    async def questions_retrieve(self, uuid: str) -> QuestionSerializerWithOptions:
        """operationId: forms_questions_retrieve"""
        data = await self._client.get(f"/api/forms/questions/{uuid}/")
        return QuestionSerializerWithOptions.model_validate(data)

    async def questions_update(self, uuid: str, body: QuestionRequest) -> Question:
        """operationId: forms_questions_update"""
        data = await self._client.put(
            f"/api/forms/questions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Question.model_validate(data)

    async def questions_partial_update(self, uuid: str, body: PatchedQuestionRequest) -> Question:
        """operationId: forms_questions_partial_update"""
        data = await self._client.patch(
            f"/api/forms/questions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Question.model_validate(data)

    async def questions_destroy(self, uuid: str) -> None:
        """operationId: forms_questions_destroy"""
        await self._client.delete(f"/api/forms/questions/{uuid}/")

    async def questions_answer_create(self, uuid: str, body: QuestionRequest) -> Question:
        """operationId: forms_questions_answer_create"""
        data = await self._client.post(
            f"/api/forms/questions/{uuid}/answer/", json=body.model_dump(exclude_none=True)
        )
        return Question.model_validate(data)
