# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    GPTChatCompletion,
    GPTPrompt,
    GPTPromptRequest,
    IncomingWebhook,
    MenuCategoryDirectiveRequest,
    MenuTextRefactorResponse,
    PaginatedGPTChatCompletionList,
    PaginatedGPTPromptList,
    PaginatedIncomingWebhookList,
    PatchedGPTPromptRequest,
)


class IntegrationsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: integrations"""

    async def gpt_chats_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedGPTChatCompletionList:
        """operationId: integrations_gpt_chats_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/integrations/gpt/chats/", params=params or None)
        return PaginatedGPTChatCompletionList.model_validate(data)

    async def gpt_chats_retrieve(self, uuid: str) -> GPTChatCompletion:
        """operationId: integrations_gpt_chats_retrieve"""
        data = await self._client.get(f"/api/integrations/gpt/chats/{uuid}/")
        return GPTChatCompletion.model_validate(data)

    async def gpt_chats_reply_create(self, uuid: str) -> GPTChatCompletion:
        """operationId: integrations_gpt_chats_reply_create"""
        data = await self._client.post(f"/api/integrations/gpt/chats/{uuid}/reply/")
        return GPTChatCompletion.model_validate(data)

    async def gpt_chats_match_challenge_create(self) -> GPTChatCompletion:
        """operationId: integrations_gpt_chats_match_challenge_create"""
        data = await self._client.post("/api/integrations/gpt/chats/match_challenge/")
        return GPTChatCompletion.model_validate(data)

    async def gpt_prompts_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedGPTPromptList:
        """operationId: integrations_gpt_prompts_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/integrations/gpt/prompts/", params=params or None)
        return PaginatedGPTPromptList.model_validate(data)

    async def gpt_prompts_create(self, body: GPTPromptRequest) -> GPTPrompt:
        """operationId: integrations_gpt_prompts_create"""
        data = await self._client.post(
            "/api/integrations/gpt/prompts/", json=body.model_dump(exclude_none=True)
        )
        return GPTPrompt.model_validate(data)

    async def gpt_prompts_retrieve(self, id: int) -> GPTPrompt:
        """operationId: integrations_gpt_prompts_retrieve"""
        data = await self._client.get(f"/api/integrations/gpt/prompts/{id}/")
        return GPTPrompt.model_validate(data)

    async def gpt_prompts_update(self, id: int, body: GPTPromptRequest) -> GPTPrompt:
        """operationId: integrations_gpt_prompts_update"""
        data = await self._client.put(
            f"/api/integrations/gpt/prompts/{id}/", json=body.model_dump(exclude_none=True)
        )
        return GPTPrompt.model_validate(data)

    async def gpt_prompts_partial_update(self, id: int, body: PatchedGPTPromptRequest) -> GPTPrompt:
        """operationId: integrations_gpt_prompts_partial_update"""
        data = await self._client.patch(
            f"/api/integrations/gpt/prompts/{id}/", json=body.model_dump(exclude_none=True)
        )
        return GPTPrompt.model_validate(data)

    async def gpt_prompts_destroy(self, id: int) -> None:
        """operationId: integrations_gpt_prompts_destroy"""
        await self._client.delete(f"/api/integrations/gpt/prompts/{id}/")

    async def gpt_prompts_prompts_text_refactor_create(
        self,
        refactor_key: str,
        body: MenuCategoryDirectiveRequest,
    ) -> MenuTextRefactorResponse:
        """operationId: integrations_gpt_prompts_prompts_text_refactor_create"""
        data = await self._client.post(
            f"/api/integrations/gpt/prompts/prompts/text-refactor/{refactor_key}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuTextRefactorResponse.model_validate(data)

    async def incoming_webhooks_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedIncomingWebhookList:
        """operationId: integrations_incoming_webhooks_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/integrations/incoming-webhooks/", params=params or None)
        return PaginatedIncomingWebhookList.model_validate(data)

    async def incoming_webhooks_retrieve(self, uuid: str) -> IncomingWebhook:
        """operationId: integrations_incoming_webhooks_retrieve"""
        data = await self._client.get(f"/api/integrations/incoming-webhooks/{uuid}/")
        return IncomingWebhook.model_validate(data)

    async def incoming_webhooks_sample_retrieve(self) -> IncomingWebhook:
        """operationId: integrations_incoming_webhooks_sample_retrieve"""
        data = await self._client.get("/api/integrations/incoming-webhooks/sample/")
        return IncomingWebhook.model_validate(data)

    async def slack_commands_create(self) -> Any:
        """operationId: integrations_slack_commands_create"""
        data = await self._client.post("/api/integrations/slack-commands/")
        return data
