# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Lead,
    LeadRequest,
    PaginatedLeadList,
    PatchedLeadRequest,
    RandomLeadRequestRequest,
    RandomLeadResponse,
    TwoStepsVerification,
    TwoStepsVerificationRequest,
)


class LeadsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: leads"""

    async def list(
        self,
        *,
        city: str | None = None,
        collector: int | None = None,
        gender: str | None = None,
        has_phonenumber: bool | None = None,
        is_sandbox: bool | None = None,
        limit: int | None = None,
        name__startswith: str | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedLeadList:
        """operationId: leads_list"""
        params: dict[str, Any] = {}
        if city is not None:
            params["city"] = city
        if collector is not None:
            params["collector"] = collector
        if gender is not None:
            params["gender"] = gender
        if has_phonenumber is not None:
            params["has_phonenumber"] = has_phonenumber
        if is_sandbox is not None:
            params["is_sandbox"] = is_sandbox
        if limit is not None:
            params["limit"] = limit
        if name__startswith is not None:
            params["name__startswith"] = name__startswith
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/leads/", params=params or None)
        return PaginatedLeadList.model_validate(data)

    async def create(self, body: LeadRequest) -> Lead:
        """operationId: leads_create"""
        data = await self._client.post("/api/leads/", json=body.model_dump(exclude_none=True))
        return Lead.model_validate(data)

    async def retrieve(self, uuid: str) -> Lead:
        """operationId: leads_retrieve"""
        data = await self._client.get(f"/api/leads/{uuid}/")
        return Lead.model_validate(data)

    async def update(self, uuid: str, body: LeadRequest) -> Lead:
        """operationId: leads_update"""
        data = await self._client.put(
            f"/api/leads/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Lead.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedLeadRequest) -> Lead:
        """operationId: leads_partial_update"""
        data = await self._client.patch(
            f"/api/leads/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Lead.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: leads_destroy"""
        await self._client.delete(f"/api/leads/{uuid}/")

    async def start_verification_create(self, uuid: str, body: LeadRequest) -> Lead:
        """operationId: leads_start_verification_create"""
        data = await self._client.post(
            f"/api/leads/{uuid}/start-verification/", json=body.model_dump(exclude_none=True)
        )
        return Lead.model_validate(data)

    async def stats_retrieve(self, uuid: str) -> Lead:
        """operationId: leads_stats_retrieve"""
        data = await self._client.get(f"/api/leads/{uuid}/stats/")
        return Lead.model_validate(data)

    async def verify_create(
        self, uuid: str, body: TwoStepsVerificationRequest
    ) -> TwoStepsVerification:
        """operationId: leads_verify_create"""
        data = await self._client.post(
            f"/api/leads/{uuid}/verify/", json=body.model_dump(exclude_none=True)
        )
        return TwoStepsVerification.model_validate(data)

    async def random_lead_create(self, body: RandomLeadRequestRequest) -> RandomLeadResponse:
        """operationId: leads_random_lead_create"""
        data = await self._client.post(
            "/api/leads/random-lead/", json=body.model_dump(exclude_none=True)
        )
        return RandomLeadResponse.model_validate(data)
