# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    LoyaltyCard,
    LoyaltyCardAddPointsResponse,
    LoyaltyCardAdminPointsRequest,
    LoyaltyCardApplyToOrderRequest,
    LoyaltyCardApplyToOrderResponse,
    LoyaltyCardBalanceMessageRequest,
    LoyaltyCardBalancePhoneRequest,
    LoyaltyCardCreateRequest,
    LoyaltyCardRemovePointsResponse,
    LoyaltyCardSendBalanceBulkResponse,
    LoyaltyCardSendBalanceResponse,
    LoyaltyCardTransaction,
    LoyaltyCardTransferRequest,
    LoyaltyCardTransferResponse,
    PaginatedLoyaltyCardList,
    PaginatedLoyaltyCardTransactionList,
)


class LoyaltyCardsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: loyalty-cards"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedLoyaltyCardList:
        """operationId: loyalty_cards_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/loyalty-cards/", params=params or None)
        return PaginatedLoyaltyCardList.model_validate(data)

    async def create(self, body: LoyaltyCardCreateRequest) -> Any:
        """operationId: loyalty_cards_create"""
        data = await self._client.post(
            "/api/loyalty-cards/", json=body.model_dump(exclude_none=True)
        )
        return data

    async def transactions_list(
        self,
        loyalty_card_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedLoyaltyCardTransactionList:
        """operationId: loyalty_cards_transactions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/loyalty-cards/{loyalty_card_uuid}/transactions/", params=params or None
        )
        return PaginatedLoyaltyCardTransactionList.model_validate(data)

    async def transactions_retrieve(
        self, loyalty_card_uuid: str, uuid: str
    ) -> LoyaltyCardTransaction:
        """operationId: loyalty_cards_transactions_retrieve"""
        data = await self._client.get(
            f"/api/loyalty-cards/{loyalty_card_uuid}/transactions/{uuid}/"
        )
        return LoyaltyCardTransaction.model_validate(data)

    async def retrieve(self, uuid: str) -> LoyaltyCard:
        """operationId: loyalty_cards_retrieve"""
        data = await self._client.get(f"/api/loyalty-cards/{uuid}/")
        return LoyaltyCard.model_validate(data)

    async def add_points_create(
        self, uuid: str, body: LoyaltyCardAdminPointsRequest
    ) -> LoyaltyCardAddPointsResponse:
        """operationId: loyalty_cards_add_points_create"""
        data = await self._client.post(
            f"/api/loyalty-cards/{uuid}/add-points/", json=body.model_dump(exclude_none=True)
        )
        return LoyaltyCardAddPointsResponse.model_validate(data)

    async def apply_to_order_create(
        self,
        uuid: str,
        body: LoyaltyCardApplyToOrderRequest,
    ) -> LoyaltyCardApplyToOrderResponse:
        """operationId: loyalty_cards_apply_to_order_create"""
        data = await self._client.post(
            f"/api/loyalty-cards/{uuid}/apply-to-order/", json=body.model_dump(exclude_none=True)
        )
        return LoyaltyCardApplyToOrderResponse.model_validate(data)

    async def remove_points_create(
        self, uuid: str, body: LoyaltyCardAdminPointsRequest
    ) -> LoyaltyCardRemovePointsResponse:
        """operationId: loyalty_cards_remove_points_create"""
        data = await self._client.post(
            f"/api/loyalty-cards/{uuid}/remove-points/", json=body.model_dump(exclude_none=True)
        )
        return LoyaltyCardRemovePointsResponse.model_validate(data)

    async def send_balance_whatsapp_create_2(
        self,
        uuid: str,
        body: LoyaltyCardBalanceMessageRequest,
    ) -> LoyaltyCardSendBalanceResponse:
        """operationId: loyalty_cards_send_balance_whatsapp_create_2"""
        data = await self._client.post(
            f"/api/loyalty-cards/{uuid}/send-balance-whatsapp/",
            json=body.model_dump(exclude_none=True),
        )
        return LoyaltyCardSendBalanceResponse.model_validate(data)

    async def transfer_create(
        self, uuid: str, body: LoyaltyCardTransferRequest
    ) -> LoyaltyCardTransferResponse:
        """operationId: loyalty_cards_transfer_create"""
        data = await self._client.post(
            f"/api/loyalty-cards/{uuid}/transfer/", json=body.model_dump(exclude_none=True)
        )
        return LoyaltyCardTransferResponse.model_validate(data)

    async def send_balance_whatsapp_create(
        self, body: LoyaltyCardBalanceMessageRequest
    ) -> LoyaltyCardSendBalanceBulkResponse:
        """operationId: loyalty_cards_send_balance_whatsapp_create"""
        data = await self._client.post(
            "/api/loyalty-cards/send-balance-whatsapp/", json=body.model_dump(exclude_none=True)
        )
        return LoyaltyCardSendBalanceBulkResponse.model_validate(data)

    async def send_to_phonenumber_create(self, body: LoyaltyCardBalancePhoneRequest) -> Any:
        """operationId: loyalty_cards_send_to_phonenumber_create"""
        data = await self._client.post(
            "/api/loyalty-cards/send-to-phonenumber/", json=body.model_dump(exclude_none=True)
        )
        return data
