# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import AddStickerMessageRequest, Message


class MessagesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: messages"""

    async def conversations_messages_sticker_create(
        self,
        conversation_uuid: str,
        body: AddStickerMessageRequest,
    ) -> Message:
        """operationId: conversations_messages_sticker_create"""
        data = await self._client.post(
            f"/api/conversations/{conversation_uuid}/messages/sticker/",
            json=body.model_dump(exclude_none=True),
        )
        return Message.model_validate(data)
