# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    OperatingCost,
    OperatingCostRequest,
    PaginatedOperatingCostList,
    PatchedOperatingCostRequest,
)


class OperatingCostsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: operating-costs"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedOperatingCostList:
        """operationId: operating_costs_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/operating-costs/", params=params or None)
        return PaginatedOperatingCostList.model_validate(data)

    async def create(self, body: OperatingCostRequest) -> OperatingCost:
        """operationId: operating_costs_create"""
        data = await self._client.post(
            "/api/operating-costs/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCost.model_validate(data)

    async def retrieve(self, uuid: str) -> OperatingCost:
        """operationId: operating_costs_retrieve"""
        data = await self._client.get(f"/api/operating-costs/{uuid}/")
        return OperatingCost.model_validate(data)

    async def update(self, uuid: str, body: OperatingCostRequest) -> OperatingCost:
        """operationId: operating_costs_update"""
        data = await self._client.put(
            f"/api/operating-costs/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCost.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedOperatingCostRequest) -> OperatingCost:
        """operationId: operating_costs_partial_update"""
        data = await self._client.patch(
            f"/api/operating-costs/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCost.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: operating_costs_destroy"""
        await self._client.delete(f"/api/operating-costs/{uuid}/")
