# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    OperatingCostCategory,
    OperatingCostCategoryRequest,
    PaginatedOperatingCostCategoryList,
    PatchedOperatingCostCategoryRequest,
)


class OperatingCostCategoriesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: operating-cost-categories"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedOperatingCostCategoryList:
        """operationId: operating_cost_categories_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/operating-cost-categories/", params=params or None)
        return PaginatedOperatingCostCategoryList.model_validate(data)

    async def create(self, body: OperatingCostCategoryRequest) -> OperatingCostCategory:
        """operationId: operating_cost_categories_create"""
        data = await self._client.post(
            "/api/operating-cost-categories/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCostCategory.model_validate(data)

    async def retrieve(self, uuid: str) -> OperatingCostCategory:
        """operationId: operating_cost_categories_retrieve"""
        data = await self._client.get(f"/api/operating-cost-categories/{uuid}/")
        return OperatingCostCategory.model_validate(data)

    async def update(self, uuid: str, body: OperatingCostCategoryRequest) -> OperatingCostCategory:
        """operationId: operating_cost_categories_update"""
        data = await self._client.put(
            f"/api/operating-cost-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCostCategory.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedOperatingCostCategoryRequest
    ) -> OperatingCostCategory:
        """operationId: operating_cost_categories_partial_update"""
        data = await self._client.patch(
            f"/api/operating-cost-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return OperatingCostCategory.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: operating_cost_categories_destroy"""
        await self._client.delete(f"/api/operating-cost-categories/{uuid}/")
