# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    CreateOrganizationRequest,
    CreateOrganizationResponse,
    Domain,
    DomainRequest,
    FailedSitePingResult,
    Organization,
    OrganizationRequest,
    OrganizationSanboxSettings,
    OrganizationSerializerWithSandboxPipelines,
    OrganizationSerializerWithSandboxPipelinesRequest,
    OrganizationSettings,
    OrganizationWhiteLabelSettings,
    PaginatedDomainList,
    PaginatedFailedSitePingResultList,
    PaginatedOrganizationList,
    PaginatedSiteToTestList,
    PaginatedTokenList,
    PaginatedUserSerializerWithProfileList,
    PatchedDomainRequest,
    PatchedOrganizationRequest,
    PatchedOrganizationSettingsRequest,
    PatchedOrganizationWhiteLabelSettingsRequest,
    PatchedSiteToTestUpdateRequest,
    PatchedTokenRequest,
    PatchedUserSerializerWithProfileRequest,
    PublicWhiteLabelResponse,
    SiteToTest,
    SiteToTestRequest,
    SiteToTestUpdate,
    SiteToTestUpdateRequest,
    Token,
    TokenRequest,
    UserSerializerWithProfile,
    UserSerializerWithProfileRequest,
    WhiteLabelLookupRequest,
)


class OrganizationsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: organizations"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedOrganizationList:
        """operationId: organizations_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/organizations/", params=params or None)
        return PaginatedOrganizationList.model_validate(data)

    async def create(self, body: CreateOrganizationRequest) -> CreateOrganizationResponse:
        """operationId: organizations_create"""
        data = await self._client.post(
            "/api/organizations/", json=body.model_dump(exclude_none=True)
        )
        return CreateOrganizationResponse.model_validate(data)

    async def domains_list(
        self,
        organization_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedDomainList:
        """operationId: organizations_domains_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/domains/", params=params or None
        )
        return PaginatedDomainList.model_validate(data)

    async def domains_create(self, organization_uuid: str, body: DomainRequest) -> Domain:
        """operationId: organizations_domains_create"""
        data = await self._client.post(
            f"/api/organizations/{organization_uuid}/domains/",
            json=body.model_dump(exclude_none=True),
        )
        return Domain.model_validate(data)

    async def domains_retrieve(self, organization_uuid: str, uuid: str) -> Domain:
        """operationId: organizations_domains_retrieve"""
        data = await self._client.get(f"/api/organizations/{organization_uuid}/domains/{uuid}/")
        return Domain.model_validate(data)

    async def domains_update(
        self,
        organization_uuid: str,
        uuid: str,
        body: DomainRequest,
    ) -> Domain:
        """operationId: organizations_domains_update"""
        data = await self._client.put(
            f"/api/organizations/{organization_uuid}/domains/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Domain.model_validate(data)

    async def domains_partial_update(
        self,
        organization_uuid: str,
        uuid: str,
        body: PatchedDomainRequest,
    ) -> Domain:
        """operationId: organizations_domains_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{organization_uuid}/domains/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Domain.model_validate(data)

    async def domains_destroy(self, organization_uuid: str, uuid: str) -> None:
        """operationId: organizations_domains_destroy"""
        await self._client.delete(f"/api/organizations/{organization_uuid}/domains/{uuid}/")

    async def sites_list(
        self,
        organization_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedSiteToTestList:
        """operationId: organizations_sites_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/sites/", params=params or None
        )
        return PaginatedSiteToTestList.model_validate(data)

    async def sites_create(self, organization_uuid: str, body: SiteToTestRequest) -> SiteToTest:
        """operationId: organizations_sites_create"""
        data = await self._client.post(
            f"/api/organizations/{organization_uuid}/sites/",
            json=body.model_dump(exclude_none=True),
        )
        return SiteToTest.model_validate(data)

    async def sites_failed_pings_list(
        self,
        organization_uuid: str,
        site_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedFailedSitePingResultList:
        """operationId: organizations_sites_failed_pings_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/sites/{site_uuid}/failed-pings/",
            params=params or None,
        )
        return PaginatedFailedSitePingResultList.model_validate(data)

    async def sites_failed_pings_retrieve(
        self,
        organization_uuid: str,
        site_uuid: str,
        uuid: str,
    ) -> FailedSitePingResult:
        """operationId: organizations_sites_failed_pings_retrieve"""
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/sites/{site_uuid}/failed-pings/{uuid}/"
        )
        return FailedSitePingResult.model_validate(data)

    async def sites_retrieve(self, organization_uuid: str, uuid: str) -> SiteToTest:
        """operationId: organizations_sites_retrieve"""
        data = await self._client.get(f"/api/organizations/{organization_uuid}/sites/{uuid}/")
        return SiteToTest.model_validate(data)

    async def sites_update(
        self,
        organization_uuid: str,
        uuid: str,
        body: SiteToTestUpdateRequest,
    ) -> SiteToTestUpdate:
        """operationId: organizations_sites_update"""
        data = await self._client.put(
            f"/api/organizations/{organization_uuid}/sites/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return SiteToTestUpdate.model_validate(data)

    async def sites_partial_update(
        self,
        organization_uuid: str,
        uuid: str,
        body: PatchedSiteToTestUpdateRequest,
    ) -> SiteToTestUpdate:
        """operationId: organizations_sites_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{organization_uuid}/sites/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return SiteToTestUpdate.model_validate(data)

    async def sites_destroy(self, organization_uuid: str, uuid: str) -> None:
        """operationId: organizations_sites_destroy"""
        await self._client.delete(f"/api/organizations/{organization_uuid}/sites/{uuid}/")

    async def tokens_list(
        self,
        organization_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedTokenList:
        """operationId: organizations_tokens_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/tokens/", params=params or None
        )
        return PaginatedTokenList.model_validate(data)

    async def tokens_create(self, organization_uuid: str, body: TokenRequest) -> Token:
        """operationId: organizations_tokens_create"""
        data = await self._client.post(
            f"/api/organizations/{organization_uuid}/tokens/",
            json=body.model_dump(exclude_none=True),
        )
        return Token.model_validate(data)

    async def tokens_retrieve(self, organization_uuid: str, uuid: str) -> Token:
        """operationId: organizations_tokens_retrieve"""
        data = await self._client.get(f"/api/organizations/{organization_uuid}/tokens/{uuid}/")
        return Token.model_validate(data)

    async def tokens_update(self, organization_uuid: str, uuid: str, body: TokenRequest) -> Token:
        """operationId: organizations_tokens_update"""
        data = await self._client.put(
            f"/api/organizations/{organization_uuid}/tokens/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Token.model_validate(data)

    async def tokens_partial_update(
        self,
        organization_uuid: str,
        uuid: str,
        body: PatchedTokenRequest,
    ) -> Token:
        """operationId: organizations_tokens_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{organization_uuid}/tokens/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Token.model_validate(data)

    async def tokens_destroy(self, organization_uuid: str, uuid: str) -> None:
        """operationId: organizations_tokens_destroy"""
        await self._client.delete(f"/api/organizations/{organization_uuid}/tokens/{uuid}/")

    async def users_list(
        self,
        organization_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedUserSerializerWithProfileList:
        """operationId: organizations_users_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/organizations/{organization_uuid}/users/", params=params or None
        )
        return PaginatedUserSerializerWithProfileList.model_validate(data)

    async def users_create(
        self,
        organization_uuid: str,
        body: UserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: organizations_users_create"""
        data = await self._client.post(
            f"/api/organizations/{organization_uuid}/users/",
            json=body.model_dump(exclude_none=True),
        )
        return UserSerializerWithProfile.model_validate(data)

    async def users_retrieve(
        self, organization_uuid: str, username: str
    ) -> UserSerializerWithProfile:
        """operationId: organizations_users_retrieve"""
        data = await self._client.get(f"/api/organizations/{organization_uuid}/users/{username}/")
        return UserSerializerWithProfile.model_validate(data)

    async def users_update(
        self,
        organization_uuid: str,
        username: str,
        body: UserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: organizations_users_update"""
        data = await self._client.put(
            f"/api/organizations/{organization_uuid}/users/{username}/",
            json=body.model_dump(exclude_none=True),
        )
        return UserSerializerWithProfile.model_validate(data)

    async def users_partial_update(
        self,
        organization_uuid: str,
        username: str,
        body: PatchedUserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: organizations_users_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{organization_uuid}/users/{username}/",
            json=body.model_dump(exclude_none=True),
        )
        return UserSerializerWithProfile.model_validate(data)

    async def users_destroy(self, organization_uuid: str, username: str) -> None:
        """operationId: organizations_users_destroy"""
        await self._client.delete(f"/api/organizations/{organization_uuid}/users/{username}/")

    async def users_login_as_create(
        self,
        organization_uuid: str,
        username: str,
        body: UserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: organizations_users_login_as_create"""
        data = await self._client.post(
            f"/api/organizations/{organization_uuid}/users/{username}/login-as/",
            json=body.model_dump(exclude_none=True),
        )
        return UserSerializerWithProfile.model_validate(data)

    async def retrieve(self, uuid: str) -> Organization:
        """operationId: organizations_retrieve"""
        data = await self._client.get(f"/api/organizations/{uuid}/")
        return Organization.model_validate(data)

    async def update(self, uuid: str, body: OrganizationRequest) -> Organization:
        """operationId: organizations_update"""
        data = await self._client.put(
            f"/api/organizations/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Organization.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedOrganizationRequest) -> Organization:
        """operationId: organizations_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Organization.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: organizations_destroy"""
        await self._client.delete(f"/api/organizations/{uuid}/")

    async def sandbox_settings_retrieve(self, uuid: str) -> OrganizationSanboxSettings:
        """operationId: organizations_sandbox_settings_retrieve"""
        data = await self._client.get(f"/api/organizations/{uuid}/sandbox-settings/")
        return OrganizationSanboxSettings.model_validate(data)

    async def sandbox_settings_partial_update(self, uuid: str) -> OrganizationSanboxSettings:
        """operationId: organizations_sandbox_settings_partial_update"""
        data = await self._client.patch(f"/api/organizations/{uuid}/sandbox-settings/")
        return OrganizationSanboxSettings.model_validate(data)

    async def sandboxes_retrieve(self, uuid: str) -> OrganizationSerializerWithSandboxPipelines:
        """operationId: organizations_sandboxes_retrieve"""
        data = await self._client.get(f"/api/organizations/{uuid}/sandboxes/")
        return OrganizationSerializerWithSandboxPipelines.model_validate(data)

    async def sandboxes_create(
        self,
        uuid: str,
        body: OrganizationSerializerWithSandboxPipelinesRequest,
    ) -> OrganizationSerializerWithSandboxPipelines:
        """operationId: organizations_sandboxes_create"""
        data = await self._client.post(
            f"/api/organizations/{uuid}/sandboxes/", json=body.model_dump(exclude_none=True)
        )
        return OrganizationSerializerWithSandboxPipelines.model_validate(data)

    async def settings_retrieve(self, uuid: str) -> OrganizationSettings:
        """operationId: organizations_settings_retrieve"""
        data = await self._client.get(f"/api/organizations/{uuid}/settings/")
        return OrganizationSettings.model_validate(data)

    async def settings_partial_update(
        self,
        uuid: str,
        body: PatchedOrganizationSettingsRequest,
    ) -> OrganizationSettings:
        """operationId: organizations_settings_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{uuid}/settings/", json=body.model_dump(exclude_none=True)
        )
        return OrganizationSettings.model_validate(data)

    async def white_label_retrieve(self, uuid: str) -> OrganizationWhiteLabelSettings:
        """operationId: organizations_white_label_retrieve"""
        data = await self._client.get(f"/api/organizations/{uuid}/white-label/")
        return OrganizationWhiteLabelSettings.model_validate(data)

    async def white_label_partial_update(
        self,
        uuid: str,
        body: PatchedOrganizationWhiteLabelSettingsRequest,
    ) -> OrganizationWhiteLabelSettings:
        """operationId: organizations_white_label_partial_update"""
        data = await self._client.patch(
            f"/api/organizations/{uuid}/white-label/", json=body.model_dump(exclude_none=True)
        )
        return OrganizationWhiteLabelSettings.model_validate(data)

    async def public_white_label_lookup_create(
        self, body: WhiteLabelLookupRequest
    ) -> PublicWhiteLabelResponse:
        """operationId: organizations_public_white_label_lookup_create"""
        data = await self._client.post(
            "/api/organizations/public-white-label-lookup/", json=body.model_dump(exclude_none=True)
        )
        return PublicWhiteLabelResponse.model_validate(data)

    async def raise_error_create(self, body: OrganizationRequest) -> Organization:
        """operationId: organizations_raise_error_create"""
        data = await self._client.post(
            "/api/organizations/raise-error/", json=body.model_dump(exclude_none=True)
        )
        return Organization.model_validate(data)

    async def web_app_entrypoint_retrieve(self) -> Organization:
        """operationId: organizations_web_app_entrypoint_retrieve"""
        data = await self._client.get("/api/organizations/web-app-entrypoint/")
        return Organization.model_validate(data)
