# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints


class PeopleEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: people"""

    async def organizations_incoming_webhooks_retrieve(
        self,
        model_key: str,
        organization_uuid: str,
    ) -> Any:
        """operationId: people_organizations_incoming_webhooks_retrieve"""
        data = await self._client.get(
            f"/api/people/organizations/{organization_uuid}/incoming-webhooks/{model_key}/"
        )
        return data

    async def organizations_incoming_webhooks_create(
        self,
        model_key: str,
        organization_uuid: str,
    ) -> Any:
        """operationId: people_organizations_incoming_webhooks_create"""
        data = await self._client.post(
            f"/api/people/organizations/{organization_uuid}/incoming-webhooks/{model_key}/"
        )
        return data
