# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    CloneOrganization,
    CloneOrganizationRequest,
    PaginatedPipelineRunList,
    PipelineRun,
)


class PipelineRunsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: pipeline-runs"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedPipelineRunList:
        """operationId: pipeline_runs_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/pipeline-runs/", params=params or None)
        return PaginatedPipelineRunList.model_validate(data)

    async def retrieve(self, uuid: str) -> PipelineRun:
        """operationId: pipeline_runs_retrieve"""
        data = await self._client.get(f"/api/pipeline-runs/{uuid}/")
        return PipelineRun.model_validate(data)

    async def update(self, uuid: str) -> PipelineRun:
        """operationId: pipeline_runs_update"""
        data = await self._client.put(f"/api/pipeline-runs/{uuid}/")
        return PipelineRun.model_validate(data)

    async def partial_update(self, uuid: str) -> PipelineRun:
        """operationId: pipeline_runs_partial_update"""
        data = await self._client.patch(f"/api/pipeline-runs/{uuid}/")
        return PipelineRun.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: pipeline_runs_destroy"""
        await self._client.delete(f"/api/pipeline-runs/{uuid}/")

    async def reset_create(self, uuid: str) -> PipelineRun:
        """operationId: pipeline_runs_reset_create"""
        data = await self._client.post(f"/api/pipeline-runs/{uuid}/reset/")
        return PipelineRun.model_validate(data)

    async def run_pipe_create(self, uuid: str) -> PipelineRun:
        """operationId: pipeline_runs_run_pipe_create"""
        data = await self._client.post(f"/api/pipeline-runs/{uuid}/run-pipe/")
        return PipelineRun.model_validate(data)

    async def clone_organization_create(self, body: CloneOrganizationRequest) -> CloneOrganization:
        """operationId: pipeline_runs_clone_organization_create"""
        data = await self._client.post(
            "/api/pipeline-runs/clone-organization/", json=body.model_dump(exclude_none=True)
        )
        return CloneOrganization.model_validate(data)

    async def entrypoint_list_retrieve(self) -> PipelineRun:
        """operationId: pipeline_runs_entrypoint_list_retrieve"""
        data = await self._client.get("/api/pipeline-runs/entrypoint-list/")
        return PipelineRun.model_validate(data)
