# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedRestaurantPromotionList,
    PatchedRestaurantPromotionRequest,
    RestaurantPromotion,
    RestaurantPromotionRequest,
)


class PromotionsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: promotions"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedRestaurantPromotionList:
        """operationId: promotions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/promotions/", params=params or None)
        return PaginatedRestaurantPromotionList.model_validate(data)

    async def create(self, body: RestaurantPromotionRequest) -> RestaurantPromotion:
        """operationId: promotions_create"""
        data = await self._client.post("/api/promotions/", json=body.model_dump(exclude_none=True))
        return RestaurantPromotion.model_validate(data)

    async def retrieve(self, uuid: str) -> RestaurantPromotion:
        """operationId: promotions_retrieve"""
        data = await self._client.get(f"/api/promotions/{uuid}/")
        return RestaurantPromotion.model_validate(data)

    async def update(self, uuid: str, body: RestaurantPromotionRequest) -> RestaurantPromotion:
        """operationId: promotions_update"""
        data = await self._client.put(
            f"/api/promotions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantPromotion.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedRestaurantPromotionRequest
    ) -> RestaurantPromotion:
        """operationId: promotions_partial_update"""
        data = await self._client.patch(
            f"/api/promotions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantPromotion.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: promotions_destroy"""
        await self._client.delete(f"/api/promotions/{uuid}/")
