# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedReadingDeviceList,
    PatchedReadingDeviceRequest,
    ReadingDevice,
    ReadingDeviceRequest,
)


class ReadingDevicesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: reading-devices"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedReadingDeviceList:
        """operationId: reading_devices_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/reading-devices/", params=params or None)
        return PaginatedReadingDeviceList.model_validate(data)

    async def create(self, body: ReadingDeviceRequest) -> ReadingDevice:
        """operationId: reading_devices_create"""
        data = await self._client.post(
            "/api/reading-devices/", json=body.model_dump(exclude_none=True)
        )
        return ReadingDevice.model_validate(data)

    async def retrieve(self, uuid: str) -> ReadingDevice:
        """operationId: reading_devices_retrieve"""
        data = await self._client.get(f"/api/reading-devices/{uuid}/")
        return ReadingDevice.model_validate(data)

    async def update(self, uuid: str, body: ReadingDeviceRequest) -> ReadingDevice:
        """operationId: reading_devices_update"""
        data = await self._client.put(
            f"/api/reading-devices/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return ReadingDevice.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedReadingDeviceRequest) -> ReadingDevice:
        """operationId: reading_devices_partial_update"""
        data = await self._client.patch(
            f"/api/reading-devices/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return ReadingDevice.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: reading_devices_destroy"""
        await self._client.delete(f"/api/reading-devices/{uuid}/")
