# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    CreateUpdateRecipeMenuItem,
    CreateUpdateRecipeMenuItemRequest,
    IngredientLine,
    IngredientLineRequest,
    PaginatedIngredientLineList,
    PaginatedRecipeList,
    PaginatedRecipeMenuItemList,
    PaginatedRecipeOutcomeList,
    PatchedCreateUpdateRecipeMenuItemRequest,
    PatchedIngredientLineRequest,
    PatchedRecipeCreateUpdateRequest,
    PatchedRecipeOutcomeRequest,
    Recipe,
    RecipeCreateUpdate,
    RecipeCreateUpdateRequest,
    RecipeMenuItem,
    RecipeOutcome,
    RecipeOutcomeRequest,
    RecipeRequest,
)


class RecipesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: recipes"""

    async def list(
        self,
        *,
        is_active: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedRecipeList:
        """operationId: recipes_list"""
        params: dict[str, Any] = {}
        if is_active is not None:
            params["is_active"] = is_active
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/recipes/", params=params or None)
        return PaginatedRecipeList.model_validate(data)

    async def create(self, body: RecipeCreateUpdateRequest) -> RecipeCreateUpdate:
        """operationId: recipes_create"""
        data = await self._client.post("/api/recipes/", json=body.model_dump(exclude_none=True))
        return RecipeCreateUpdate.model_validate(data)

    async def ingredients_list(
        self,
        recipe_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedIngredientLineList:
        """operationId: recipes_ingredients_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/recipes/{recipe_uuid}/ingredients/", params=params or None
        )
        return PaginatedIngredientLineList.model_validate(data)

    async def ingredients_create(
        self, recipe_uuid: str, body: IngredientLineRequest
    ) -> IngredientLine:
        """operationId: recipes_ingredients_create"""
        data = await self._client.post(
            f"/api/recipes/{recipe_uuid}/ingredients/", json=body.model_dump(exclude_none=True)
        )
        return IngredientLine.model_validate(data)

    async def ingredients_retrieve(self, recipe_uuid: str, uuid: str) -> IngredientLine:
        """operationId: recipes_ingredients_retrieve"""
        data = await self._client.get(f"/api/recipes/{recipe_uuid}/ingredients/{uuid}/")
        return IngredientLine.model_validate(data)

    async def ingredients_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: IngredientLineRequest,
    ) -> IngredientLine:
        """operationId: recipes_ingredients_update"""
        data = await self._client.put(
            f"/api/recipes/{recipe_uuid}/ingredients/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return IngredientLine.model_validate(data)

    async def ingredients_partial_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: PatchedIngredientLineRequest,
    ) -> IngredientLine:
        """operationId: recipes_ingredients_partial_update"""
        data = await self._client.patch(
            f"/api/recipes/{recipe_uuid}/ingredients/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return IngredientLine.model_validate(data)

    async def ingredients_destroy(self, recipe_uuid: str, uuid: str) -> None:
        """operationId: recipes_ingredients_destroy"""
        await self._client.delete(f"/api/recipes/{recipe_uuid}/ingredients/{uuid}/")

    async def menu_items_list(
        self,
        recipe_uuid: str,
        *,
        is_active: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        override_unit: str | None = None,
    ) -> PaginatedRecipeMenuItemList:
        """operationId: recipes_menu_items_list"""
        params: dict[str, Any] = {}
        if is_active is not None:
            params["is_active"] = is_active
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if override_unit is not None:
            params["override_unit"] = override_unit
        data = await self._client.get(
            f"/api/recipes/{recipe_uuid}/menu-items/", params=params or None
        )
        return PaginatedRecipeMenuItemList.model_validate(data)

    async def menu_items_create(
        self,
        recipe_uuid: str,
        body: CreateUpdateRecipeMenuItemRequest,
    ) -> CreateUpdateRecipeMenuItem:
        """operationId: recipes_menu_items_create"""
        data = await self._client.post(
            f"/api/recipes/{recipe_uuid}/menu-items/", json=body.model_dump(exclude_none=True)
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def menu_items_retrieve(self, recipe_uuid: str, uuid: str) -> RecipeMenuItem:
        """operationId: recipes_menu_items_retrieve"""
        data = await self._client.get(f"/api/recipes/{recipe_uuid}/menu-items/{uuid}/")
        return RecipeMenuItem.model_validate(data)

    async def menu_items_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: CreateUpdateRecipeMenuItemRequest,
    ) -> CreateUpdateRecipeMenuItem:
        """operationId: recipes_menu_items_update"""
        data = await self._client.put(
            f"/api/recipes/{recipe_uuid}/menu-items/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def menu_items_partial_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: PatchedCreateUpdateRecipeMenuItemRequest,
    ) -> CreateUpdateRecipeMenuItem:
        """operationId: recipes_menu_items_partial_update"""
        data = await self._client.patch(
            f"/api/recipes/{recipe_uuid}/menu-items/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def menu_items_destroy(self, recipe_uuid: str, uuid: str) -> None:
        """operationId: recipes_menu_items_destroy"""
        await self._client.delete(f"/api/recipes/{recipe_uuid}/menu-items/{uuid}/")

    async def outcomes_list(
        self,
        recipe_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedRecipeOutcomeList:
        """operationId: recipes_outcomes_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/recipes/{recipe_uuid}/outcomes/", params=params or None
        )
        return PaginatedRecipeOutcomeList.model_validate(data)

    async def outcomes_create(self, recipe_uuid: str, body: RecipeOutcomeRequest) -> RecipeOutcome:
        """operationId: recipes_outcomes_create"""
        data = await self._client.post(
            f"/api/recipes/{recipe_uuid}/outcomes/", json=body.model_dump(exclude_none=True)
        )
        return RecipeOutcome.model_validate(data)

    async def outcomes_retrieve(self, recipe_uuid: str, uuid: str) -> RecipeOutcome:
        """operationId: recipes_outcomes_retrieve"""
        data = await self._client.get(f"/api/recipes/{recipe_uuid}/outcomes/{uuid}/")
        return RecipeOutcome.model_validate(data)

    async def outcomes_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: RecipeOutcomeRequest,
    ) -> RecipeOutcome:
        """operationId: recipes_outcomes_update"""
        data = await self._client.put(
            f"/api/recipes/{recipe_uuid}/outcomes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RecipeOutcome.model_validate(data)

    async def outcomes_partial_update(
        self,
        recipe_uuid: str,
        uuid: str,
        body: PatchedRecipeOutcomeRequest,
    ) -> RecipeOutcome:
        """operationId: recipes_outcomes_partial_update"""
        data = await self._client.patch(
            f"/api/recipes/{recipe_uuid}/outcomes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RecipeOutcome.model_validate(data)

    async def outcomes_destroy(self, recipe_uuid: str, uuid: str) -> None:
        """operationId: recipes_outcomes_destroy"""
        await self._client.delete(f"/api/recipes/{recipe_uuid}/outcomes/{uuid}/")

    async def retrieve(self, uuid: str) -> Recipe:
        """operationId: recipes_retrieve"""
        data = await self._client.get(f"/api/recipes/{uuid}/")
        return Recipe.model_validate(data)

    async def update(self, uuid: str, body: RecipeCreateUpdateRequest) -> RecipeCreateUpdate:
        """operationId: recipes_update"""
        data = await self._client.put(
            f"/api/recipes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RecipeCreateUpdate.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedRecipeCreateUpdateRequest
    ) -> RecipeCreateUpdate:
        """operationId: recipes_partial_update"""
        data = await self._client.patch(
            f"/api/recipes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RecipeCreateUpdate.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: recipes_destroy"""
        await self._client.delete(f"/api/recipes/{uuid}/")

    async def fast_recipes_create(self, body: RecipeRequest) -> Recipe:
        """operationId: recipes_fast_recipes_create"""
        data = await self._client.post(
            "/api/recipes/fast-recipes/", json=body.model_dump(exclude_none=True)
        )
        return Recipe.model_validate(data)
