# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    CreateUpdateRecipeMenuItem,
    CreateUpdateRecipeMenuItemRequest,
    PaginatedRecipeMenuItemList,
    PatchedCreateUpdateRecipeMenuItemRequest,
    RecipeMenuItem,
)


class RecipeMenuItemsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: recipe-menu-items"""

    async def list(
        self,
        *,
        is_active: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        override_unit: str | None = None,
    ) -> PaginatedRecipeMenuItemList:
        """operationId: recipe_menu_items_list"""
        params: dict[str, Any] = {}
        if is_active is not None:
            params["is_active"] = is_active
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if override_unit is not None:
            params["override_unit"] = override_unit
        data = await self._client.get("/api/recipe-menu-items/", params=params or None)
        return PaginatedRecipeMenuItemList.model_validate(data)

    async def create(self, body: CreateUpdateRecipeMenuItemRequest) -> CreateUpdateRecipeMenuItem:
        """operationId: recipe_menu_items_create"""
        data = await self._client.post(
            "/api/recipe-menu-items/", json=body.model_dump(exclude_none=True)
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def retrieve(self, uuid: str) -> RecipeMenuItem:
        """operationId: recipe_menu_items_retrieve"""
        data = await self._client.get(f"/api/recipe-menu-items/{uuid}/")
        return RecipeMenuItem.model_validate(data)

    async def update(
        self, uuid: str, body: CreateUpdateRecipeMenuItemRequest
    ) -> CreateUpdateRecipeMenuItem:
        """operationId: recipe_menu_items_update"""
        data = await self._client.put(
            f"/api/recipe-menu-items/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def partial_update(
        self,
        uuid: str,
        body: PatchedCreateUpdateRecipeMenuItemRequest,
    ) -> CreateUpdateRecipeMenuItem:
        """operationId: recipe_menu_items_partial_update"""
        data = await self._client.patch(
            f"/api/recipe-menu-items/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return CreateUpdateRecipeMenuItem.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: recipe_menu_items_destroy"""
        await self._client.delete(f"/api/recipe-menu-items/{uuid}/")
