# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    ChangeLead,
    Driver,
    DriverCreate,
    DriverCreateRequest,
    DriverRequest,
    ExtraCharge,
    ExtraChargeCreate,
    ExtraChargeCreateRequest,
    ExtraChargeRequest,
    FloorPlan,
    FloorPlanElement,
    FloorPlanElementWrite,
    FloorPlanElementWriteRequest,
    FloorPlanWrite,
    FloorPlanWriteRequest,
    Lead,
    LeadRequest,
    Menu,
    MenuCategory,
    MenuCategoryRequest,
    MenuItem,
    MenuItemCategoryAssignment,
    MenuItemCategoryAssignmentRequest,
    MenuItemRequest,
    MenuMenuCategoryAssignment,
    MenuMenuCategoryAssignmentRequest,
    MenuRequest,
    OperatingCost,
    OperatingCostRequest,
    OperatingDay,
    OperatingDayRequest,
    PaginatedDriverList,
    PaginatedExtraChargeList,
    PaginatedFloorPlanElementList,
    PaginatedFloorPlanList,
    PaginatedMenuCategoryList,
    PaginatedMenuItemCategoryAssignmentList,
    PaginatedMenuItemList,
    PaginatedMenuList,
    PaginatedMenuMenuCategoryAssignmentList,
    PaginatedOperatingCostList,
    PaginatedOperatingDayList,
    PaginatedReadingDeviceList,
    PaginatedRestaurantList,
    PaginatedRestaurantModeList,
    PaginatedRestaurantOrderListList,
    PaginatedRestaurantOrderPrintingRequestList,
    PaginatedRestaurantOrderPrintingRequestRecipientList,
    PaginatedRestaurantPromotionList,
    PaginatedRouteList,
    PaginatedTTSMessageList,
    PaginatedTableList,
    PatchedChangeLeadRequest,
    PatchedDriverRequest,
    PatchedExtraChargeRequest,
    PatchedFloorPlanElementWriteRequest,
    PatchedFloorPlanWriteRequest,
    PatchedMenuCategoryRequest,
    PatchedMenuItemCategoryAssignmentRequest,
    PatchedMenuItemRequest,
    PatchedMenuMenuCategoryAssignmentRequest,
    PatchedMenuRequest,
    PatchedOperatingCostRequest,
    PatchedOperatingDayRequest,
    PatchedPrivateRestaurantOrderRequest,
    PatchedReadingDeviceRequest,
    PatchedRestaurantModeRequest,
    PatchedRestaurantOrderPrintingRequestRecipientRequest,
    PatchedRestaurantOrderPrintingRequestRequest,
    PatchedRestaurantOrderUpdateRequest,
    PatchedRestaurantPromotionRequest,
    PatchedRestaurantRequest,
    PatchedRouteRequest,
    PatchedTTSMessageRequest,
    PatchedTableWriteRequest,
    PrintingErrorInput,
    PrintingErrorInputRequest,
    PrivateRestaurantOrder,
    PrivateRestaurantOrderRequest,
    ReadingDevice,
    ReadingDeviceRequest,
    Restaurant,
    RestaurantMode,
    RestaurantModeRequest,
    RestaurantOrderCreate,
    RestaurantOrderCreateRequest,
    RestaurantOrderPrintingRequest,
    RestaurantOrderPrintingRequestRecipient,
    RestaurantOrderPrintingRequestRecipientRequest,
    RestaurantOrderPrintingRequestRequest,
    RestaurantOrderUpdate,
    RestaurantOrderUpdateRequest,
    RestaurantPromotion,
    RestaurantPromotionRequest,
    RestaurantRequest,
    Route,
    RouteCreate,
    RouteCreateRequest,
    RouteDetail,
    RouteRequest,
    SandboxOrderRequestRequest,
    SandboxOrderResponse,
    SetMenu,
    SetMenuRequest,
    TTSMessage,
    TTSMessageReadByDeviceInput,
    TTSMessageReadByDeviceInputRequest,
    TTSMessageRequest,
    Table,
    TableRequest,
    TableWrite,
    TableWriteRequest,
    V2FullMenu,
    WarRoomAsyncRequestRequest,
)


class RestaurantsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: restaurants"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedRestaurantList:
        """operationId: restaurants_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/restaurants/", params=params or None)
        return PaginatedRestaurantList.model_validate(data)

    async def create(self, body: RestaurantRequest) -> Restaurant:
        """operationId: restaurants_create"""
        data = await self._client.post("/api/restaurants/", json=body.model_dump(exclude_none=True))
        return Restaurant.model_validate(data)

    async def drivers_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedDriverList:
        """operationId: restaurants_drivers_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/drivers/", params=params or None
        )
        return PaginatedDriverList.model_validate(data)

    async def drivers_create(self, restaurant_uuid: str, body: DriverCreateRequest) -> DriverCreate:
        """operationId: restaurants_drivers_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/drivers/", json=body.model_dump(exclude_none=True)
        )
        return DriverCreate.model_validate(data)

    async def drivers_retrieve(self, restaurant_uuid: str, uuid: str) -> Driver:
        """operationId: restaurants_drivers_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/drivers/{uuid}/")
        return Driver.model_validate(data)

    async def drivers_update(self, restaurant_uuid: str, uuid: str, body: DriverRequest) -> Driver:
        """operationId: restaurants_drivers_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/drivers/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Driver.model_validate(data)

    async def drivers_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedDriverRequest,
    ) -> Driver:
        """operationId: restaurants_drivers_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/drivers/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Driver.model_validate(data)

    async def drivers_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_drivers_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/drivers/{uuid}/")

    async def drivers_active_route_retrieve(self, restaurant_uuid: str, uuid: str) -> Driver:
        """operationId: restaurants_drivers_active_route_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/drivers/{uuid}/active_route/"
        )
        return Driver.model_validate(data)

    async def floor_plans_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedFloorPlanList:
        """operationId: restaurants_floor_plans_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/", params=params or None
        )
        return PaginatedFloorPlanList.model_validate(data)

    async def floor_plans_create(
        self, restaurant_uuid: str, body: FloorPlanWriteRequest
    ) -> FloorPlanWrite:
        """operationId: restaurants_floor_plans_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanWrite.model_validate(data)

    async def floor_plans_elements_list(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedFloorPlanElementList:
        """operationId: restaurants_floor_plans_elements_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/",
            params=params or None,
        )
        return PaginatedFloorPlanElementList.model_validate(data)

    async def floor_plans_elements_create(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        body: FloorPlanElementWriteRequest,
    ) -> FloorPlanElementWrite:
        """operationId: restaurants_floor_plans_elements_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanElementWrite.model_validate(data)

    async def floor_plans_elements_retrieve(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> FloorPlanElement:
        """operationId: restaurants_floor_plans_elements_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/{uuid}/"
        )
        return FloorPlanElement.model_validate(data)

    async def floor_plans_elements_update(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: FloorPlanElementWriteRequest,
    ) -> FloorPlanElementWrite:
        """operationId: restaurants_floor_plans_elements_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanElementWrite.model_validate(data)

    async def floor_plans_elements_partial_update(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedFloorPlanElementWriteRequest,
    ) -> FloorPlanElementWrite:
        """operationId: restaurants_floor_plans_elements_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanElementWrite.model_validate(data)

    async def floor_plans_elements_destroy(
        self,
        floor_plan_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: restaurants_floor_plans_elements_destroy"""
        await self._client.delete(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{floor_plan_uuid}/elements/{uuid}/"
        )

    async def floor_plans_retrieve(self, restaurant_uuid: str, uuid: str) -> FloorPlan:
        """operationId: restaurants_floor_plans_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/floor-plans/{uuid}/")
        return FloorPlan.model_validate(data)

    async def floor_plans_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: FloorPlanWriteRequest,
    ) -> FloorPlanWrite:
        """operationId: restaurants_floor_plans_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanWrite.model_validate(data)

    async def floor_plans_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedFloorPlanWriteRequest,
    ) -> FloorPlanWrite:
        """operationId: restaurants_floor_plans_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/floor-plans/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return FloorPlanWrite.model_validate(data)

    async def floor_plans_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_floor_plans_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/floor-plans/{uuid}/")

    async def menus_list_2(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedMenuList:
        """operationId: restaurants_menus_list_2"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/menus/", params=params or None
        )
        return PaginatedMenuList.model_validate(data)

    async def menus_create_2(self, restaurant_uuid: str, body: MenuRequest) -> Menu:
        """operationId: restaurants_menus_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/menus/", json=body.model_dump(exclude_none=True)
        )
        return Menu.model_validate(data)

    async def menus_categories_list(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedMenuCategoryList:
        """operationId: restaurants_menus_categories_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/",
            params=params or None,
        )
        return PaginatedMenuCategoryList.model_validate(data)

    async def menus_categories_create(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        body: MenuCategoryRequest,
    ) -> MenuCategory:
        """operationId: restaurants_menus_categories_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuCategory.model_validate(data)

    async def menus_categories_retrieve(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> MenuCategory:
        """operationId: restaurants_menus_categories_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/{uuid}/"
        )
        return MenuCategory.model_validate(data)

    async def menus_categories_update(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: MenuCategoryRequest,
    ) -> MenuCategory:
        """operationId: restaurants_menus_categories_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuCategory.model_validate(data)

    async def menus_categories_partial_update(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedMenuCategoryRequest,
    ) -> MenuCategory:
        """operationId: restaurants_menus_categories_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuCategory.model_validate(data)

    async def menus_categories_destroy(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: restaurants_menus_categories_destroy"""
        await self._client.delete(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/categories/{uuid}/"
        )

    async def menus_category_assignments_list(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedMenuMenuCategoryAssignmentList:
        """operationId: restaurants_menus_category_assignments_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/",
            params=params or None,
        )
        return PaginatedMenuMenuCategoryAssignmentList.model_validate(data)

    async def menus_category_assignments_create(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        body: MenuMenuCategoryAssignmentRequest,
    ) -> MenuMenuCategoryAssignment:
        """operationId: restaurants_menus_category_assignments_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuMenuCategoryAssignment.model_validate(data)

    async def menus_category_assignments_retrieve(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> MenuMenuCategoryAssignment:
        """operationId: restaurants_menus_category_assignments_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/{uuid}/"
        )
        return MenuMenuCategoryAssignment.model_validate(data)

    async def menus_category_assignments_update(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: MenuMenuCategoryAssignmentRequest,
    ) -> MenuMenuCategoryAssignment:
        """operationId: restaurants_menus_category_assignments_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuMenuCategoryAssignment.model_validate(data)

    async def menus_category_assignments_partial_update(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedMenuMenuCategoryAssignmentRequest,
    ) -> MenuMenuCategoryAssignment:
        """operationId: restaurants_menus_category_assignments_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuMenuCategoryAssignment.model_validate(data)

    async def menus_category_assignments_destroy(
        self,
        menu_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: restaurants_menus_category_assignments_destroy"""
        await self._client.delete(
            f"/api/restaurants/{restaurant_uuid}/menus/{menu_uuid}/category-assignments/{uuid}/"
        )

    async def menus_retrieve_2(self, restaurant_uuid: str, uuid: str) -> Menu:
        """operationId: restaurants_menus_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/menus/{uuid}/")
        return Menu.model_validate(data)

    async def menus_update_2(self, restaurant_uuid: str, uuid: str, body: MenuRequest) -> Menu:
        """operationId: restaurants_menus_update_2"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/menus/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Menu.model_validate(data)

    async def menus_partial_update_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedMenuRequest,
    ) -> Menu:
        """operationId: restaurants_menus_partial_update_2"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/menus/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Menu.model_validate(data)

    async def menus_destroy_2(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_menus_destroy_2"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/menus/{uuid}/")

    async def menus_full_menu_retrieve_2(self, restaurant_uuid: str) -> V2FullMenu:
        """operationId: restaurants_menus_full_menu_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/menus/full-menu/")
        return V2FullMenu.model_validate(data)

    async def messages_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedTTSMessageList:
        """operationId: restaurants_messages_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/messages/", params=params or None
        )
        return PaginatedTTSMessageList.model_validate(data)

    async def messages_create(self, restaurant_uuid: str, body: TTSMessageRequest) -> TTSMessage:
        """operationId: restaurants_messages_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/messages/", json=body.model_dump(exclude_none=True)
        )
        return TTSMessage.model_validate(data)

    async def messages_retrieve(self, restaurant_uuid: str, uuid: str) -> TTSMessage:
        """operationId: restaurants_messages_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/messages/{uuid}/")
        return TTSMessage.model_validate(data)

    async def messages_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: TTSMessageRequest,
    ) -> TTSMessage:
        """operationId: restaurants_messages_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/messages/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return TTSMessage.model_validate(data)

    async def messages_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedTTSMessageRequest,
    ) -> TTSMessage:
        """operationId: restaurants_messages_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/messages/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return TTSMessage.model_validate(data)

    async def messages_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_messages_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/messages/{uuid}/")

    async def messages_mark_as_read_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: TTSMessageReadByDeviceInputRequest,
    ) -> TTSMessageReadByDeviceInput:
        """operationId: restaurants_messages_mark_as_read_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/messages/{uuid}/mark-as-read/",
            json=body.model_dump(exclude_none=True),
        )
        return TTSMessageReadByDeviceInput.model_validate(data)

    async def modes_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedRestaurantModeList:
        """operationId: restaurants_modes_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/modes/", params=params or None
        )
        return PaginatedRestaurantModeList.model_validate(data)

    async def modes_create(
        self, restaurant_uuid: str, body: RestaurantModeRequest
    ) -> RestaurantMode:
        """operationId: restaurants_modes_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/modes/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantMode.model_validate(data)

    async def modes_retrieve(self, restaurant_uuid: str, uuid: str) -> RestaurantMode:
        """operationId: restaurants_modes_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/modes/{uuid}/")
        return RestaurantMode.model_validate(data)

    async def modes_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantModeRequest,
    ) -> RestaurantMode:
        """operationId: restaurants_modes_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/modes/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantMode.model_validate(data)

    async def modes_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRestaurantModeRequest,
    ) -> RestaurantMode:
        """operationId: restaurants_modes_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/modes/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantMode.model_validate(data)

    async def modes_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_modes_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/modes/{uuid}/")

    async def operating_costs_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedOperatingCostList:
        """operationId: restaurants_operating_costs_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/operating-costs/", params=params or None
        )
        return PaginatedOperatingCostList.model_validate(data)

    async def operating_costs_create(
        self,
        restaurant_uuid: str,
        body: OperatingCostRequest,
    ) -> OperatingCost:
        """operationId: restaurants_operating_costs_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/operating-costs/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingCost.model_validate(data)

    async def operating_costs_retrieve(self, restaurant_uuid: str, uuid: str) -> OperatingCost:
        """operationId: restaurants_operating_costs_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/operating-costs/{uuid}/")
        return OperatingCost.model_validate(data)

    async def operating_costs_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: OperatingCostRequest,
    ) -> OperatingCost:
        """operationId: restaurants_operating_costs_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/operating-costs/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingCost.model_validate(data)

    async def operating_costs_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedOperatingCostRequest,
    ) -> OperatingCost:
        """operationId: restaurants_operating_costs_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/operating-costs/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingCost.model_validate(data)

    async def operating_costs_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_operating_costs_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/operating-costs/{uuid}/")

    async def operating_days_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedOperatingDayList:
        """operationId: restaurants_operating_days_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/operating-days/", params=params or None
        )
        return PaginatedOperatingDayList.model_validate(data)

    async def operating_days_create(
        self,
        restaurant_uuid: str,
        body: OperatingDayRequest,
    ) -> OperatingDay:
        """operationId: restaurants_operating_days_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/operating-days/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingDay.model_validate(data)

    async def operating_days_retrieve(self, restaurant_uuid: str, uuid: str) -> OperatingDay:
        """operationId: restaurants_operating_days_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/")
        return OperatingDay.model_validate(data)

    async def operating_days_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: OperatingDayRequest,
    ) -> OperatingDay:
        """operationId: restaurants_operating_days_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingDay.model_validate(data)

    async def operating_days_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedOperatingDayRequest,
    ) -> OperatingDay:
        """operationId: restaurants_operating_days_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingDay.model_validate(data)

    async def operating_days_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_operating_days_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/")

    async def operating_days_close_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: OperatingDayRequest,
    ) -> OperatingDay:
        """operationId: restaurants_operating_days_close_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/close/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingDay.model_validate(data)

    async def operating_days_open_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: OperatingDayRequest,
    ) -> OperatingDay:
        """operationId: restaurants_operating_days_open_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/operating-days/{uuid}/open/",
            json=body.model_dump(exclude_none=True),
        )
        return OperatingDay.model_validate(data)

    async def operating_days_today_retrieve(self, restaurant_uuid: str) -> OperatingDay:
        """operationId: restaurants_operating_days_today_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/operating-days/today/")
        return OperatingDay.model_validate(data)

    async def orders_list_2(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedRestaurantOrderListList:
        """operationId: restaurants_orders_list_2"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/", params=params or None
        )
        return PaginatedRestaurantOrderListList.model_validate(data)

    async def orders_create_2(
        self,
        restaurant_uuid: str,
        body: RestaurantOrderCreateRequest,
    ) -> RestaurantOrderCreate:
        """operationId: restaurants_orders_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantOrderCreate.model_validate(data)

    async def orders_extra_charges_list(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedExtraChargeList:
        """operationId: restaurants_orders_extra_charges_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/",
            params=params or None,
        )
        return PaginatedExtraChargeList.model_validate(data)

    async def orders_extra_charges_create(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        body: ExtraChargeCreateRequest,
    ) -> ExtraChargeCreate:
        """operationId: restaurants_orders_extra_charges_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/",
            json=body.model_dump(exclude_none=True),
        )
        return ExtraChargeCreate.model_validate(data)

    async def orders_extra_charges_retrieve(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> ExtraCharge:
        """operationId: restaurants_orders_extra_charges_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/{uuid}/"
        )
        return ExtraCharge.model_validate(data)

    async def orders_extra_charges_update(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: ExtraChargeRequest,
    ) -> ExtraCharge:
        """operationId: restaurants_orders_extra_charges_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return ExtraCharge.model_validate(data)

    async def orders_extra_charges_partial_update(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedExtraChargeRequest,
    ) -> ExtraCharge:
        """operationId: restaurants_orders_extra_charges_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return ExtraCharge.model_validate(data)

    async def orders_extra_charges_destroy(
        self,
        order_uuid: str,
        restaurant_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: restaurants_orders_extra_charges_destroy"""
        await self._client.delete(
            f"/api/restaurants/{restaurant_uuid}/orders/{order_uuid}/extra-charges/{uuid}/"
        )

    async def orders_retrieve_2(self, restaurant_uuid: str, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_update_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantOrderUpdateRequest,
    ) -> RestaurantOrderUpdate:
        """operationId: restaurants_orders_update_2"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderUpdate.model_validate(data)

    async def orders_partial_update_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRestaurantOrderUpdateRequest,
    ) -> RestaurantOrderUpdate:
        """operationId: restaurants_orders_partial_update_2"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderUpdate.model_validate(data)

    async def orders_destroy_2(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_orders_destroy_2"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/")

    async def orders_cancel_order_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_cancel_order_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/cancel-order/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_change_lead_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: LeadRequest,
    ) -> Lead:
        """operationId: restaurants_orders_change_lead_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/change-lead/",
            json=body.model_dump(exclude_none=True),
        )
        return Lead.model_validate(data)

    async def orders_change_lead_partial_update_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedChangeLeadRequest,
    ) -> ChangeLead:
        """operationId: restaurants_orders_change_lead_partial_update_2"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/change-lead/",
            json=body.model_dump(exclude_none=True),
        )
        return ChangeLead.model_validate(data)

    async def orders_confirm_order_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_confirm_order_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/confirm-order/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_confirmation_message_retrieve_2(
        self,
        restaurant_uuid: str,
        uuid: str,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_confirmation_message_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/confirmation-message/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_create_tracking_code_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_create_tracking_code_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/create-tracking-code/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_extend_grace_period_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_extend_grace_period_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/extend-grace-period/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_logs_retrieve_2(
        self, restaurant_uuid: str, uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_logs_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/logs/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_notify_confirmation_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_notify_confirmation_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/notify-confirmation/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_on_delivery_message_retrieve_2(
        self,
        restaurant_uuid: str,
        uuid: str,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_on_delivery_message_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/on-delivery-message/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_order_delivered_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_order_delivered_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/order-delivered/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_request_printing_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_request_printing_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/request-printing/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_from_delivered_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_from_delivered_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/revert-from-delivered/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_from_delivery_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_from_delivery_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/revert-from-delivery/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_to_confirmed_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_to_confirmed_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/revert-to-confirmed/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_rush_grace_period_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_rush_grace_period_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/rush-grace-period/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_address_partial_update_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedPrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_address_partial_update_2"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/set-address/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_due_date_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_due_date_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/set-due-date/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_order_type_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_order_type_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/set-order-type/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_start_delivery_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_start_delivery_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/start-delivery/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_start_processing_create_2(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_start_processing_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/start-processing/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_whatsapp_message_retrieve_2(
        self, restaurant_uuid: str, uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_whatsapp_message_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/{uuid}/whatsapp-message/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_available_vehicles_retrieve_2(
        self, restaurant_uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_available_vehicles_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/available-vehicles/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_by_tracking_code_retrieve_2(
        self,
        restaurant_uuid: str,
        tracking_code: str,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_by_tracking_code_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/by-tracking-code/{tracking_code}/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_chicken_tracking_retrieve_2(
        self, restaurant_uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_chicken_tracking_retrieve_2"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/orders/chicken-tracking/"
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_dashboard_stats_retrieve_2(
        self, restaurant_uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_dashboard_stats_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/dashboard-stats/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_kanban_board_retrieve_2(self, restaurant_uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_kanban_board_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/kanban-board/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_orders_tracking_retrieve_2(
        self, restaurant_uuid: str
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_orders_tracking_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/orders-tracking/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_today_orders_retrieve_2(self, restaurant_uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_today_orders_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/today-orders/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_traffic_light_retrieve_2(self, restaurant_uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_traffic_light_retrieve_2"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/orders/traffic-light/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_war_room_async_create_2(
        self,
        restaurant_uuid: str,
        body: WarRoomAsyncRequestRequest,
    ) -> Any:
        """operationId: restaurants_orders_war_room_async_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/war-room-async/",
            json=body.model_dump(exclude_none=True),
        )
        return data

    async def orders_whatsapp_message_create_2(
        self,
        restaurant_uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_whatsapp_message_create_2"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/orders/whatsapp-message/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def printing_request_recipients_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedRestaurantOrderPrintingRequestRecipientList:
        """operationId: restaurants_printing_request_recipients_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/",
            params=params or None,
        )
        return PaginatedRestaurantOrderPrintingRequestRecipientList.model_validate(data)

    async def printing_request_recipients_create(
        self,
        restaurant_uuid: str,
        body: RestaurantOrderPrintingRequestRecipientRequest,
    ) -> RestaurantOrderPrintingRequestRecipient:
        """operationId: restaurants_printing_request_recipients_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequestRecipient.model_validate(data)

    async def printing_request_recipients_retrieve(
        self, restaurant_uuid: str, uuid: str
    ) -> RestaurantOrderPrintingRequestRecipient:
        """operationId: restaurants_printing_request_recipients_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/"
        )
        return RestaurantOrderPrintingRequestRecipient.model_validate(data)

    async def printing_request_recipients_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantOrderPrintingRequestRecipientRequest,
    ) -> RestaurantOrderPrintingRequestRecipient:
        """operationId: restaurants_printing_request_recipients_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequestRecipient.model_validate(data)

    async def printing_request_recipients_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRestaurantOrderPrintingRequestRecipientRequest,
    ) -> RestaurantOrderPrintingRequestRecipient:
        """operationId: restaurants_printing_request_recipients_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequestRecipient.model_validate(data)

    async def printing_request_recipients_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_printing_request_recipients_destroy"""
        await self._client.delete(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/"
        )

    async def printing_request_recipients_mark_as_error_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PrintingErrorInputRequest,
    ) -> PrintingErrorInput:
        """operationId: restaurants_printing_request_recipients_mark_as_error_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/mark-as-error/",
            json=body.model_dump(exclude_none=True),
        )
        return PrintingErrorInput.model_validate(data)

    async def printing_request_recipients_mark_as_printed_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantOrderPrintingRequestRecipientRequest,
    ) -> RestaurantOrderPrintingRequestRecipient:
        """operationId: restaurants_printing_request_recipients_mark_as_printed_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/printing-request-recipients/{uuid}/mark-as-printed/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequestRecipient.model_validate(data)

    async def printing_requests_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedRestaurantOrderPrintingRequestList:
        """operationId: restaurants_printing_requests_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/printing-requests/", params=params or None
        )
        return PaginatedRestaurantOrderPrintingRequestList.model_validate(data)

    async def printing_requests_create(
        self,
        restaurant_uuid: str,
        body: RestaurantOrderPrintingRequestRequest,
    ) -> RestaurantOrderPrintingRequest:
        """operationId: restaurants_printing_requests_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/printing-requests/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequest.model_validate(data)

    async def printing_requests_retrieve(
        self, restaurant_uuid: str, uuid: str
    ) -> RestaurantOrderPrintingRequest:
        """operationId: restaurants_printing_requests_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/printing-requests/{uuid}/"
        )
        return RestaurantOrderPrintingRequest.model_validate(data)

    async def printing_requests_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantOrderPrintingRequestRequest,
    ) -> RestaurantOrderPrintingRequest:
        """operationId: restaurants_printing_requests_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/printing-requests/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequest.model_validate(data)

    async def printing_requests_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRestaurantOrderPrintingRequestRequest,
    ) -> RestaurantOrderPrintingRequest:
        """operationId: restaurants_printing_requests_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/printing-requests/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantOrderPrintingRequest.model_validate(data)

    async def printing_requests_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_printing_requests_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/printing-requests/{uuid}/")

    async def promotions_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedRestaurantPromotionList:
        """operationId: restaurants_promotions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/promotions/", params=params or None
        )
        return PaginatedRestaurantPromotionList.model_validate(data)

    async def promotions_create(
        self,
        restaurant_uuid: str,
        body: RestaurantPromotionRequest,
    ) -> RestaurantPromotion:
        """operationId: restaurants_promotions_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/promotions/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantPromotion.model_validate(data)

    async def promotions_retrieve(self, restaurant_uuid: str, uuid: str) -> RestaurantPromotion:
        """operationId: restaurants_promotions_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/promotions/{uuid}/")
        return RestaurantPromotion.model_validate(data)

    async def promotions_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: RestaurantPromotionRequest,
    ) -> RestaurantPromotion:
        """operationId: restaurants_promotions_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/promotions/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantPromotion.model_validate(data)

    async def promotions_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRestaurantPromotionRequest,
    ) -> RestaurantPromotion:
        """operationId: restaurants_promotions_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/promotions/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return RestaurantPromotion.model_validate(data)

    async def promotions_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_promotions_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/promotions/{uuid}/")

    async def reading_devices_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedReadingDeviceList:
        """operationId: restaurants_reading_devices_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/reading-devices/", params=params or None
        )
        return PaginatedReadingDeviceList.model_validate(data)

    async def reading_devices_create(
        self,
        restaurant_uuid: str,
        body: ReadingDeviceRequest,
    ) -> ReadingDevice:
        """operationId: restaurants_reading_devices_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/reading-devices/",
            json=body.model_dump(exclude_none=True),
        )
        return ReadingDevice.model_validate(data)

    async def reading_devices_retrieve(self, restaurant_uuid: str, uuid: str) -> ReadingDevice:
        """operationId: restaurants_reading_devices_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/reading-devices/{uuid}/")
        return ReadingDevice.model_validate(data)

    async def reading_devices_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: ReadingDeviceRequest,
    ) -> ReadingDevice:
        """operationId: restaurants_reading_devices_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/reading-devices/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return ReadingDevice.model_validate(data)

    async def reading_devices_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedReadingDeviceRequest,
    ) -> ReadingDevice:
        """operationId: restaurants_reading_devices_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/reading-devices/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return ReadingDevice.model_validate(data)

    async def reading_devices_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_reading_devices_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/reading-devices/{uuid}/")

    async def routes_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedRouteList:
        """operationId: restaurants_routes_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/routes/", params=params or None
        )
        return PaginatedRouteList.model_validate(data)

    async def routes_create(self, restaurant_uuid: str, body: RouteCreateRequest) -> RouteCreate:
        """operationId: restaurants_routes_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/routes/", json=body.model_dump(exclude_none=True)
        )
        return RouteCreate.model_validate(data)

    async def routes_retrieve(self, restaurant_uuid: str, uuid: str) -> RouteDetail:
        """operationId: restaurants_routes_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/routes/{uuid}/")
        return RouteDetail.model_validate(data)

    async def routes_update(self, restaurant_uuid: str, uuid: str, body: RouteRequest) -> Route:
        """operationId: restaurants_routes_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/routes/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Route.model_validate(data)

    async def routes_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedRouteRequest,
    ) -> Route:
        """operationId: restaurants_routes_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/routes/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return Route.model_validate(data)

    async def routes_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_routes_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/routes/{uuid}/")

    async def routes_active_route_retrieve(self, restaurant_uuid: str) -> Route:
        """operationId: restaurants_routes_active_route_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/routes/active-route/")
        return Route.model_validate(data)

    async def tables_list(
        self,
        restaurant_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedTableList:
        """operationId: restaurants_tables_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/restaurants/{restaurant_uuid}/tables/", params=params or None
        )
        return PaginatedTableList.model_validate(data)

    async def tables_create(self, restaurant_uuid: str, body: TableWriteRequest) -> TableWrite:
        """operationId: restaurants_tables_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/tables/", json=body.model_dump(exclude_none=True)
        )
        return TableWrite.model_validate(data)

    async def tables_retrieve(self, restaurant_uuid: str, uuid: str) -> Table:
        """operationId: restaurants_tables_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/")
        return Table.model_validate(data)

    async def tables_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: TableWriteRequest,
    ) -> TableWrite:
        """operationId: restaurants_tables_update"""
        data = await self._client.put(
            f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return TableWrite.model_validate(data)

    async def tables_partial_update(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: PatchedTableWriteRequest,
    ) -> TableWrite:
        """operationId: restaurants_tables_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return TableWrite.model_validate(data)

    async def tables_destroy(self, restaurant_uuid: str, uuid: str) -> None:
        """operationId: restaurants_tables_destroy"""
        await self._client.delete(f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/")

    async def tables_cancel_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: TableRequest,
    ) -> Table:
        """operationId: restaurants_tables_cancel_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/cancel/",
            json=body.model_dump(exclude_none=True),
        )
        return Table.model_validate(data)

    async def tables_close_create(
        self,
        restaurant_uuid: str,
        uuid: str,
        body: TableRequest,
    ) -> Table:
        """operationId: restaurants_tables_close_create"""
        data = await self._client.post(
            f"/api/restaurants/{restaurant_uuid}/tables/{uuid}/close/",
            json=body.model_dump(exclude_none=True),
        )
        return Table.model_validate(data)

    async def tables_today_retrieve(self, restaurant_uuid: str) -> Table:
        """operationId: restaurants_tables_today_retrieve"""
        data = await self._client.get(f"/api/restaurants/{restaurant_uuid}/tables/today/")
        return Table.model_validate(data)

    async def retrieve(self, uuid: str) -> Restaurant:
        """operationId: restaurants_retrieve"""
        data = await self._client.get(f"/api/restaurants/{uuid}/")
        return Restaurant.model_validate(data)

    async def update(self, uuid: str, body: RestaurantRequest) -> Restaurant:
        """operationId: restaurants_update"""
        data = await self._client.put(
            f"/api/restaurants/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Restaurant.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedRestaurantRequest) -> Restaurant:
        """operationId: restaurants_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Restaurant.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: restaurants_destroy"""
        await self._client.delete(f"/api/restaurants/{uuid}/")

    async def operating_day_financials_retrieve(self, uuid: str) -> Restaurant:
        """operationId: restaurants_operating_day_financials_retrieve"""
        data = await self._client.get(f"/api/restaurants/{uuid}/operating-day-financials/")
        return Restaurant.model_validate(data)

    async def random_order_create(
        self, uuid: str, body: SandboxOrderRequestRequest
    ) -> SandboxOrderResponse:
        """operationId: restaurants_random_order_create"""
        data = await self._client.post(
            f"/api/restaurants/{uuid}/random-order/", json=body.model_dump(exclude_none=True)
        )
        return SandboxOrderResponse.model_validate(data)

    async def send_tracking_url_create(self, uuid: str, body: RestaurantRequest) -> Restaurant:
        """operationId: restaurants_send_tracking_url_create"""
        data = await self._client.post(
            f"/api/restaurants/{uuid}/send-tracking-url/", json=body.model_dump(exclude_none=True)
        )
        return Restaurant.model_validate(data)

    async def set_menu_create(self, uuid: str, body: SetMenuRequest) -> SetMenu:
        """operationId: restaurants_set_menu_create"""
        data = await self._client.post(
            f"/api/restaurants/{uuid}/set-menu/", json=body.model_dump(exclude_none=True)
        )
        return SetMenu.model_validate(data)

    async def web_app_entrypoint_retrieve(self, uuid: str) -> Restaurant:
        """operationId: restaurants_web_app_entrypoint_retrieve"""
        data = await self._client.get(f"/api/restaurants/{uuid}/web-app-entrypoint/")
        return Restaurant.model_validate(data)

    async def menu_categories_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedMenuCategoryList:
        """operationId: restaurants_menu_categories_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/restaurants/menu-categories/", params=params or None)
        return PaginatedMenuCategoryList.model_validate(data)

    async def menu_categories_create(self, body: MenuCategoryRequest) -> MenuCategory:
        """operationId: restaurants_menu_categories_create"""
        data = await self._client.post(
            "/api/restaurants/menu-categories/", json=body.model_dump(exclude_none=True)
        )
        return MenuCategory.model_validate(data)

    async def menu_categories_retrieve(self, uuid: str) -> MenuCategory:
        """operationId: restaurants_menu_categories_retrieve"""
        data = await self._client.get(f"/api/restaurants/menu-categories/{uuid}/")
        return MenuCategory.model_validate(data)

    async def menu_categories_update(self, uuid: str, body: MenuCategoryRequest) -> MenuCategory:
        """operationId: restaurants_menu_categories_update"""
        data = await self._client.put(
            f"/api/restaurants/menu-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return MenuCategory.model_validate(data)

    async def menu_categories_partial_update(
        self,
        uuid: str,
        body: PatchedMenuCategoryRequest,
    ) -> MenuCategory:
        """operationId: restaurants_menu_categories_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/menu-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return MenuCategory.model_validate(data)

    async def menu_categories_destroy(self, uuid: str) -> None:
        """operationId: restaurants_menu_categories_destroy"""
        await self._client.delete(f"/api/restaurants/menu-categories/{uuid}/")

    async def menu_items_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedMenuItemList:
        """operationId: restaurants_menu_items_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/restaurants/menu-items/", params=params or None)
        return PaginatedMenuItemList.model_validate(data)

    async def menu_items_create(self, body: MenuItemRequest) -> MenuItem:
        """operationId: restaurants_menu_items_create"""
        data = await self._client.post(
            "/api/restaurants/menu-items/", json=body.model_dump(exclude_none=True)
        )
        return MenuItem.model_validate(data)

    async def menu_items_category_assignments_list(
        self,
        menu_item_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedMenuItemCategoryAssignmentList:
        """operationId: restaurants_menu_items_category_assignments_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/",
            params=params or None,
        )
        return PaginatedMenuItemCategoryAssignmentList.model_validate(data)

    async def menu_items_category_assignments_create(
        self,
        menu_item_uuid: str,
        body: MenuItemCategoryAssignmentRequest,
    ) -> MenuItemCategoryAssignment:
        """operationId: restaurants_menu_items_category_assignments_create"""
        data = await self._client.post(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuItemCategoryAssignment.model_validate(data)

    async def menu_items_category_assignments_retrieve(
        self,
        menu_item_uuid: str,
        uuid: str,
    ) -> MenuItemCategoryAssignment:
        """operationId: restaurants_menu_items_category_assignments_retrieve"""
        data = await self._client.get(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/{uuid}/"
        )
        return MenuItemCategoryAssignment.model_validate(data)

    async def menu_items_category_assignments_update(
        self,
        menu_item_uuid: str,
        uuid: str,
        body: MenuItemCategoryAssignmentRequest,
    ) -> MenuItemCategoryAssignment:
        """operationId: restaurants_menu_items_category_assignments_update"""
        data = await self._client.put(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuItemCategoryAssignment.model_validate(data)

    async def menu_items_category_assignments_partial_update(
        self,
        menu_item_uuid: str,
        uuid: str,
        body: PatchedMenuItemCategoryAssignmentRequest,
    ) -> MenuItemCategoryAssignment:
        """operationId: restaurants_menu_items_category_assignments_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return MenuItemCategoryAssignment.model_validate(data)

    async def menu_items_category_assignments_destroy(
        self,
        menu_item_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: restaurants_menu_items_category_assignments_destroy"""
        await self._client.delete(
            f"/api/restaurants/menu-items/{menu_item_uuid}/category-assignments/{uuid}/"
        )

    async def menu_items_retrieve(self, uuid: str) -> MenuItem:
        """operationId: restaurants_menu_items_retrieve"""
        data = await self._client.get(f"/api/restaurants/menu-items/{uuid}/")
        return MenuItem.model_validate(data)

    async def menu_items_update(self, uuid: str, body: MenuItemRequest) -> MenuItem:
        """operationId: restaurants_menu_items_update"""
        data = await self._client.put(
            f"/api/restaurants/menu-items/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return MenuItem.model_validate(data)

    async def menu_items_partial_update(self, uuid: str, body: PatchedMenuItemRequest) -> MenuItem:
        """operationId: restaurants_menu_items_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/menu-items/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return MenuItem.model_validate(data)

    async def menu_items_destroy(self, uuid: str) -> None:
        """operationId: restaurants_menu_items_destroy"""
        await self._client.delete(f"/api/restaurants/menu-items/{uuid}/")

    async def menus_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedMenuList:
        """operationId: restaurants_menus_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/restaurants/menus/", params=params or None)
        return PaginatedMenuList.model_validate(data)

    async def menus_create(self, body: MenuRequest) -> Menu:
        """operationId: restaurants_menus_create"""
        data = await self._client.post(
            "/api/restaurants/menus/", json=body.model_dump(exclude_none=True)
        )
        return Menu.model_validate(data)

    async def menus_retrieve(self, uuid: str) -> Menu:
        """operationId: restaurants_menus_retrieve"""
        data = await self._client.get(f"/api/restaurants/menus/{uuid}/")
        return Menu.model_validate(data)

    async def menus_update(self, uuid: str, body: MenuRequest) -> Menu:
        """operationId: restaurants_menus_update"""
        data = await self._client.put(
            f"/api/restaurants/menus/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Menu.model_validate(data)

    async def menus_partial_update(self, uuid: str, body: PatchedMenuRequest) -> Menu:
        """operationId: restaurants_menus_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/menus/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Menu.model_validate(data)

    async def menus_destroy(self, uuid: str) -> None:
        """operationId: restaurants_menus_destroy"""
        await self._client.delete(f"/api/restaurants/menus/{uuid}/")

    async def menus_full_menu_retrieve(self) -> V2FullMenu:
        """operationId: restaurants_menus_full_menu_retrieve"""
        data = await self._client.get("/api/restaurants/menus/full-menu/")
        return V2FullMenu.model_validate(data)

    async def orders_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedRestaurantOrderListList:
        """operationId: restaurants_orders_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/restaurants/orders/", params=params or None)
        return PaginatedRestaurantOrderListList.model_validate(data)

    async def orders_create(self, body: RestaurantOrderCreateRequest) -> RestaurantOrderCreate:
        """operationId: restaurants_orders_create"""
        data = await self._client.post(
            "/api/restaurants/orders/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantOrderCreate.model_validate(data)

    async def orders_retrieve(self, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/{uuid}/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_update(
        self, uuid: str, body: RestaurantOrderUpdateRequest
    ) -> RestaurantOrderUpdate:
        """operationId: restaurants_orders_update"""
        data = await self._client.put(
            f"/api/restaurants/orders/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantOrderUpdate.model_validate(data)

    async def orders_partial_update(
        self,
        uuid: str,
        body: PatchedRestaurantOrderUpdateRequest,
    ) -> RestaurantOrderUpdate:
        """operationId: restaurants_orders_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/orders/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return RestaurantOrderUpdate.model_validate(data)

    async def orders_destroy(self, uuid: str) -> None:
        """operationId: restaurants_orders_destroy"""
        await self._client.delete(f"/api/restaurants/orders/{uuid}/")

    async def orders_cancel_order_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_cancel_order_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/cancel-order/", json=body.model_dump(exclude_none=True)
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_change_lead_create(self, uuid: str, body: LeadRequest) -> Lead:
        """operationId: restaurants_orders_change_lead_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/change-lead/", json=body.model_dump(exclude_none=True)
        )
        return Lead.model_validate(data)

    async def orders_change_lead_partial_update(
        self,
        uuid: str,
        body: PatchedChangeLeadRequest,
    ) -> ChangeLead:
        """operationId: restaurants_orders_change_lead_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/orders/{uuid}/change-lead/", json=body.model_dump(exclude_none=True)
        )
        return ChangeLead.model_validate(data)

    async def orders_confirm_order_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_confirm_order_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/confirm-order/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_confirmation_message_retrieve(self, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_confirmation_message_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/{uuid}/confirmation-message/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_create_tracking_code_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_create_tracking_code_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/create-tracking-code/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_extend_grace_period_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_extend_grace_period_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/extend-grace-period/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_logs_retrieve(self, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_logs_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/{uuid}/logs/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_notify_confirmation_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_notify_confirmation_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/notify-confirmation/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_on_delivery_message_retrieve(self, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_on_delivery_message_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/{uuid}/on-delivery-message/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_order_delivered_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_order_delivered_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/order-delivered/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_request_printing_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_request_printing_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/request-printing/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_from_delivered_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_from_delivered_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/revert-from-delivered/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_from_delivery_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_from_delivery_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/revert-from-delivery/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_revert_to_confirmed_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_revert_to_confirmed_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/revert-to-confirmed/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_rush_grace_period_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_rush_grace_period_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/rush-grace-period/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_address_partial_update(
        self,
        uuid: str,
        body: PatchedPrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_address_partial_update"""
        data = await self._client.patch(
            f"/api/restaurants/orders/{uuid}/set-address/", json=body.model_dump(exclude_none=True)
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_due_date_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_due_date_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/set-due-date/", json=body.model_dump(exclude_none=True)
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_set_order_type_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_set_order_type_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/set-order-type/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_start_delivery_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_start_delivery_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/start-delivery/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_start_processing_create(
        self,
        uuid: str,
        body: PrivateRestaurantOrderRequest,
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_start_processing_create"""
        data = await self._client.post(
            f"/api/restaurants/orders/{uuid}/start-processing/",
            json=body.model_dump(exclude_none=True),
        )
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_whatsapp_message_retrieve(self, uuid: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_whatsapp_message_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/{uuid}/whatsapp-message/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_available_vehicles_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_available_vehicles_retrieve"""
        data = await self._client.get("/api/restaurants/orders/available-vehicles/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_by_tracking_code_retrieve(self, tracking_code: str) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_by_tracking_code_retrieve"""
        data = await self._client.get(f"/api/restaurants/orders/by-tracking-code/{tracking_code}/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_chicken_tracking_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_chicken_tracking_retrieve"""
        data = await self._client.get("/api/restaurants/orders/chicken-tracking/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_dashboard_stats_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_dashboard_stats_retrieve"""
        data = await self._client.get("/api/restaurants/orders/dashboard-stats/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_kanban_board_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_kanban_board_retrieve"""
        data = await self._client.get("/api/restaurants/orders/kanban-board/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_orders_tracking_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_orders_tracking_retrieve"""
        data = await self._client.get("/api/restaurants/orders/orders-tracking/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_today_orders_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_today_orders_retrieve"""
        data = await self._client.get("/api/restaurants/orders/today-orders/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_traffic_light_retrieve(self) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_traffic_light_retrieve"""
        data = await self._client.get("/api/restaurants/orders/traffic-light/")
        return PrivateRestaurantOrder.model_validate(data)

    async def orders_war_room_async_create(self, body: WarRoomAsyncRequestRequest) -> Any:
        """operationId: restaurants_orders_war_room_async_create"""
        data = await self._client.post(
            "/api/restaurants/orders/war-room-async/", json=body.model_dump(exclude_none=True)
        )
        return data

    async def orders_whatsapp_message_create(
        self, body: PrivateRestaurantOrderRequest
    ) -> PrivateRestaurantOrder:
        """operationId: restaurants_orders_whatsapp_message_create"""
        data = await self._client.post(
            "/api/restaurants/orders/whatsapp-message/", json=body.model_dump(exclude_none=True)
        )
        return PrivateRestaurantOrder.model_validate(data)
