# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    Feature,
    PaginatedFeatureList,
    PaginatedPainPointList,
    PaginatedScreenshotList,
    PaginatedServerErrorList,
    PaginatedTechDecisionList,
    PainPoint,
    Screenshot,
    ServerError,
    TechDecision,
)


class ServerEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: server"""

    async def errors_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedServerErrorList:
        """operationId: server_errors_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/server/errors/", params=params or None)
        return PaginatedServerErrorList.model_validate(data)

    async def errors_retrieve(self, code: str) -> ServerError:
        """operationId: server_errors_retrieve"""
        data = await self._client.get(f"/api/server/errors/{code}/")
        return ServerError.model_validate(data)

    async def features_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedFeatureList:
        """operationId: server_features_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/server/features/", params=params or None)
        return PaginatedFeatureList.model_validate(data)

    async def features_retrieve(self, slug: str) -> Feature:
        """operationId: server_features_retrieve"""
        data = await self._client.get(f"/api/server/features/{slug}/")
        return Feature.model_validate(data)

    async def pain_points_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedPainPointList:
        """operationId: server_pain_points_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/server/pain-points/", params=params or None)
        return PaginatedPainPointList.model_validate(data)

    async def pain_points_retrieve(self, slug: str) -> PainPoint:
        """operationId: server_pain_points_retrieve"""
        data = await self._client.get(f"/api/server/pain-points/{slug}/")
        return PainPoint.model_validate(data)

    async def screenshots_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedScreenshotList:
        """operationId: server_screenshots_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/server/screenshots/", params=params or None)
        return PaginatedScreenshotList.model_validate(data)

    async def screenshots_retrieve(self, id: int) -> Screenshot:
        """operationId: server_screenshots_retrieve"""
        data = await self._client.get(f"/api/server/screenshots/{id}/")
        return Screenshot.model_validate(data)

    async def tech_decisions_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedTechDecisionList:
        """operationId: server_tech_decisions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/server/tech-decisions/", params=params or None)
        return PaginatedTechDecisionList.model_validate(data)

    async def tech_decisions_retrieve(self, key: str) -> TechDecision:
        """operationId: server_tech_decisions_retrieve"""
        data = await self._client.get(f"/api/server/tech-decisions/{key}/")
        return TechDecision.model_validate(data)
