# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedSmartMessageTemplateList,
    PatchedSmartMessageTemplateRequest,
    SmartMessageTemplate,
    SmartMessageTemplateRequest,
)


class SmartMessageTemplatesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: smart-message-templates"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedSmartMessageTemplateList:
        """operationId: smart_message_templates_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/smart-message-templates/", params=params or None)
        return PaginatedSmartMessageTemplateList.model_validate(data)

    async def create(self, body: SmartMessageTemplateRequest) -> SmartMessageTemplate:
        """operationId: smart_message_templates_create"""
        data = await self._client.post(
            "/api/smart-message-templates/", json=body.model_dump(exclude_none=True)
        )
        return SmartMessageTemplate.model_validate(data)

    async def retrieve(self, uuid: str) -> SmartMessageTemplate:
        """operationId: smart_message_templates_retrieve"""
        data = await self._client.get(f"/api/smart-message-templates/{uuid}/")
        return SmartMessageTemplate.model_validate(data)

    async def update(self, uuid: str, body: SmartMessageTemplateRequest) -> SmartMessageTemplate:
        """operationId: smart_message_templates_update"""
        data = await self._client.put(
            f"/api/smart-message-templates/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return SmartMessageTemplate.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedSmartMessageTemplateRequest
    ) -> SmartMessageTemplate:
        """operationId: smart_message_templates_partial_update"""
        data = await self._client.patch(
            f"/api/smart-message-templates/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return SmartMessageTemplate.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: smart_message_templates_destroy"""
        await self._client.delete(f"/api/smart-message-templates/{uuid}/")
