# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedStickerList,
    PatchedStickerRequest,
    Sticker,
    StickerRequest,
)


class StickersEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stickers"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedStickerList:
        """operationId: stickers_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/stickers/", params=params or None)
        return PaginatedStickerList.model_validate(data)

    async def create(self, body: StickerRequest) -> Sticker:
        """operationId: stickers_create"""
        data = await self._client.post("/api/stickers/", json=body.model_dump(exclude_none=True))
        return Sticker.model_validate(data)

    async def retrieve(self, uuid: str) -> Sticker:
        """operationId: stickers_retrieve"""
        data = await self._client.get(f"/api/stickers/{uuid}/")
        return Sticker.model_validate(data)

    async def update(self, uuid: str, body: StickerRequest) -> Sticker:
        """operationId: stickers_update"""
        data = await self._client.put(
            f"/api/stickers/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Sticker.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedStickerRequest) -> Sticker:
        """operationId: stickers_partial_update"""
        data = await self._client.patch(
            f"/api/stickers/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Sticker.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stickers_destroy"""
        await self._client.delete(f"/api/stickers/{uuid}/")
