# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedStockCategoryList,
    PatchedStockCategoryRequest,
    StockCategory,
    StockCategoryRequest,
)


class StockCategoriesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stock-categories"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedStockCategoryList:
        """operationId: stock_categories_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/stock-categories/", params=params or None)
        return PaginatedStockCategoryList.model_validate(data)

    async def create(self, body: StockCategoryRequest) -> StockCategory:
        """operationId: stock_categories_create"""
        data = await self._client.post(
            "/api/stock-categories/", json=body.model_dump(exclude_none=True)
        )
        return StockCategory.model_validate(data)

    async def retrieve(self, uuid: str) -> StockCategory:
        """operationId: stock_categories_retrieve"""
        data = await self._client.get(f"/api/stock-categories/{uuid}/")
        return StockCategory.model_validate(data)

    async def update(self, uuid: str, body: StockCategoryRequest) -> StockCategory:
        """operationId: stock_categories_update"""
        data = await self._client.put(
            f"/api/stock-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockCategory.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedStockCategoryRequest) -> StockCategory:
        """operationId: stock_categories_partial_update"""
        data = await self._client.patch(
            f"/api/stock-categories/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockCategory.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stock_categories_destroy"""
        await self._client.delete(f"/api/stock-categories/{uuid}/")

    async def fast_product_create(self, uuid: str, body: StockCategoryRequest) -> StockCategory:
        """operationId: stock_categories_fast_product_create"""
        data = await self._client.post(
            f"/api/stock-categories/{uuid}/fast-product/", json=body.model_dump(exclude_none=True)
        )
        return StockCategory.model_validate(data)

    async def full_tree_retrieve(self, uuid: str) -> StockCategory:
        """operationId: stock_categories_full_tree_retrieve"""
        data = await self._client.get(f"/api/stock-categories/{uuid}/full-tree/")
        return StockCategory.model_validate(data)
