# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    BulkCalculateCost,
    BulkCalculateCostRequest,
    BulkRefreshErrors,
    BulkRefreshErrorsRequest,
    CalculateCost,
    CalculateCostRequest,
    FallbackCost,
    FallbackCostRequest,
    PaginatedFallbackCostList,
    PaginatedStockProductList,
    PaginatedUnitConversionProfileList,
    PatchedStockProductRequest,
    PatchedUnitConversionProfileRequest,
    StockProduct,
    StockProductRequest,
    UnitConversionProfile,
    UnitConversionProfileRequest,
)


class StockProductsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stock-products"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedStockProductList:
        """operationId: stock_products_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/stock-products/", params=params or None)
        return PaginatedStockProductList.model_validate(data)

    async def create(self, body: StockProductRequest) -> StockProduct:
        """operationId: stock_products_create"""
        data = await self._client.post(
            "/api/stock-products/", json=body.model_dump(exclude_none=True)
        )
        return StockProduct.model_validate(data)

    async def fallback_costs_list(
        self,
        product_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedFallbackCostList:
        """operationId: stock_products_fallback_costs_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get(
            f"/api/stock-products/{product_uuid}/fallback-costs/", params=params or None
        )
        return PaginatedFallbackCostList.model_validate(data)

    async def fallback_costs_create(
        self, product_uuid: str, body: FallbackCostRequest
    ) -> FallbackCost:
        """operationId: stock_products_fallback_costs_create"""
        data = await self._client.post(
            f"/api/stock-products/{product_uuid}/fallback-costs/",
            json=body.model_dump(exclude_none=True),
        )
        return FallbackCost.model_validate(data)

    async def fallback_costs_retrieve(self, product_uuid: str, uuid: str) -> FallbackCost:
        """operationId: stock_products_fallback_costs_retrieve"""
        data = await self._client.get(f"/api/stock-products/{product_uuid}/fallback-costs/{uuid}/")
        return FallbackCost.model_validate(data)

    async def unit_conversion_profiles_list(
        self,
        product_uuid: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedUnitConversionProfileList:
        """operationId: stock_products_unit_conversion_profiles_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/", params=params or None
        )
        return PaginatedUnitConversionProfileList.model_validate(data)

    async def unit_conversion_profiles_create(
        self,
        product_uuid: str,
        body: UnitConversionProfileRequest,
    ) -> UnitConversionProfile:
        """operationId: stock_products_unit_conversion_profiles_create"""
        data = await self._client.post(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/",
            json=body.model_dump(exclude_none=True),
        )
        return UnitConversionProfile.model_validate(data)

    async def unit_conversion_profiles_conversion_factors_create(
        self,
        product_uuid: str,
        profile_uuid: str,
    ) -> Any:
        """operationId: stock_products_unit_conversion_profiles_conversion_factors_create"""
        data = await self._client.post(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{profile_uuid}/conversion-factors/"
        )
        return data

    async def unit_conversion_profiles_conversion_factors_destroy(
        self,
        product_uuid: str,
        profile_uuid: str,
        uuid: str,
    ) -> None:
        """operationId: stock_products_unit_conversion_profiles_conversion_factors_destroy"""
        await self._client.delete(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{profile_uuid}/conversion-factors/{uuid}/"
        )

    async def unit_conversion_profiles_retrieve(
        self, product_uuid: str, uuid: str
    ) -> UnitConversionProfile:
        """operationId: stock_products_unit_conversion_profiles_retrieve"""
        data = await self._client.get(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{uuid}/"
        )
        return UnitConversionProfile.model_validate(data)

    async def unit_conversion_profiles_update(
        self,
        product_uuid: str,
        uuid: str,
        body: UnitConversionProfileRequest,
    ) -> UnitConversionProfile:
        """operationId: stock_products_unit_conversion_profiles_update"""
        data = await self._client.put(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return UnitConversionProfile.model_validate(data)

    async def unit_conversion_profiles_partial_update(
        self,
        product_uuid: str,
        uuid: str,
        body: PatchedUnitConversionProfileRequest,
    ) -> UnitConversionProfile:
        """operationId: stock_products_unit_conversion_profiles_partial_update"""
        data = await self._client.patch(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{uuid}/",
            json=body.model_dump(exclude_none=True),
        )
        return UnitConversionProfile.model_validate(data)

    async def unit_conversion_profiles_destroy(self, product_uuid: str, uuid: str) -> None:
        """operationId: stock_products_unit_conversion_profiles_destroy"""
        await self._client.delete(
            f"/api/stock-products/{product_uuid}/unit-conversion-profiles/{uuid}/"
        )

    async def retrieve(self, uuid: str) -> StockProduct:
        """operationId: stock_products_retrieve"""
        data = await self._client.get(f"/api/stock-products/{uuid}/")
        return StockProduct.model_validate(data)

    async def update(self, uuid: str, body: StockProductRequest) -> StockProduct:
        """operationId: stock_products_update"""
        data = await self._client.put(
            f"/api/stock-products/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockProduct.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedStockProductRequest) -> StockProduct:
        """operationId: stock_products_partial_update"""
        data = await self._client.patch(
            f"/api/stock-products/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockProduct.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stock_products_destroy"""
        await self._client.delete(f"/api/stock-products/{uuid}/")

    async def cost_calculator_create_2(
        self, uuid: str, body: CalculateCostRequest
    ) -> CalculateCost:
        """operationId: stock_products_cost_calculator_create_2"""
        data = await self._client.post(
            f"/api/stock-products/{uuid}/cost-calculator/", json=body.model_dump(exclude_none=True)
        )
        return CalculateCost.model_validate(data)

    async def refresh_errors_create_2(self, uuid: str, body: StockProductRequest) -> StockProduct:
        """operationId: stock_products_refresh_errors_create_2"""
        data = await self._client.post(
            f"/api/stock-products/{uuid}/refresh-errors/", json=body.model_dump(exclude_none=True)
        )
        return StockProduct.model_validate(data)

    async def cost_calculator_create(self, body: BulkCalculateCostRequest) -> BulkCalculateCost:
        """operationId: stock_products_cost_calculator_create"""
        data = await self._client.post(
            "/api/stock-products/cost-calculator/", json=body.model_dump(exclude_none=True)
        )
        return BulkCalculateCost.model_validate(data)

    async def refresh_errors_create(self, body: BulkRefreshErrorsRequest) -> BulkRefreshErrors:
        """operationId: stock_products_refresh_errors_create"""
        data = await self._client.post(
            "/api/stock-products/refresh-errors/", json=body.model_dump(exclude_none=True)
        )
        return BulkRefreshErrors.model_validate(data)

    async def slim_retrieve(self) -> StockProduct:
        """operationId: stock_products_slim_retrieve"""
        data = await self._client.get("/api/stock-products/slim/")
        return StockProduct.model_validate(data)
