# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedStockTransactionList,
    PatchedStockTransactionRequest,
    StockTransaction,
    StockTransactionRequest,
)


class StockTransactionsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stock-transactions"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedStockTransactionList:
        """operationId: stock_transactions_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/stock-transactions/", params=params or None)
        return PaginatedStockTransactionList.model_validate(data)

    async def create(self, body: StockTransactionRequest) -> StockTransaction:
        """operationId: stock_transactions_create"""
        data = await self._client.post(
            "/api/stock-transactions/", json=body.model_dump(exclude_none=True)
        )
        return StockTransaction.model_validate(data)

    async def retrieve(self, uuid: str) -> StockTransaction:
        """operationId: stock_transactions_retrieve"""
        data = await self._client.get(f"/api/stock-transactions/{uuid}/")
        return StockTransaction.model_validate(data)

    async def update(self, uuid: str, body: StockTransactionRequest) -> StockTransaction:
        """operationId: stock_transactions_update"""
        data = await self._client.put(
            f"/api/stock-transactions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockTransaction.model_validate(data)

    async def partial_update(
        self, uuid: str, body: PatchedStockTransactionRequest
    ) -> StockTransaction:
        """operationId: stock_transactions_partial_update"""
        data = await self._client.patch(
            f"/api/stock-transactions/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StockTransaction.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stock_transactions_destroy"""
        await self._client.delete(f"/api/stock-transactions/{uuid}/")

    async def expired_create(self) -> Any:
        """operationId: stock_transactions_expired_create"""
        data = await self._client.post("/api/stock-transactions/expired/")
        return data

    async def produced_create(self) -> Any:
        """operationId: stock_transactions_produced_create"""
        data = await self._client.post("/api/stock-transactions/produced/")
        return data

    async def reserved_create(self) -> Any:
        """operationId: stock_transactions_reserved_create"""
        data = await self._client.post("/api/stock-transactions/reserved/")
        return data

    async def stock_in_create(self) -> Any:
        """operationId: stock_transactions_stock_in_create"""
        data = await self._client.post("/api/stock-transactions/stock_in/")
        return data

    async def stock_in_invoice_create(self) -> Any:
        """operationId: stock_transactions_stock_in_invoice_create"""
        data = await self._client.post("/api/stock-transactions/stock_in_invoice/")
        return data

    async def stock_out_create(self) -> Any:
        """operationId: stock_transactions_stock_out_create"""
        data = await self._client.post("/api/stock-transactions/stock_out/")
        return data
