# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedStopList,
    PatchedStopRequest,
    Stop,
    StopDetail,
    StopRequest,
)


class StopsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stops"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedStopList:
        """operationId: stops_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/stops/", params=params or None)
        return PaginatedStopList.model_validate(data)

    async def create(self, body: StopRequest) -> Stop:
        """operationId: stops_create"""
        data = await self._client.post("/api/stops/", json=body.model_dump(exclude_none=True))
        return Stop.model_validate(data)

    async def retrieve(self, uuid: str) -> StopDetail:
        """operationId: stops_retrieve"""
        data = await self._client.get(f"/api/stops/{uuid}/")
        return StopDetail.model_validate(data)

    async def update(self, uuid: str, body: StopRequest) -> Stop:
        """operationId: stops_update"""
        data = await self._client.put(
            f"/api/stops/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Stop.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedStopRequest) -> Stop:
        """operationId: stops_partial_update"""
        data = await self._client.patch(
            f"/api/stops/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Stop.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stops_destroy"""
        await self._client.delete(f"/api/stops/{uuid}/")
