# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedStopAddressList,
    PatchedStopAddressRequest,
    StopAddress,
    StopAddressRequest,
)


class StopAddressesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: stop-addresses"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedStopAddressList:
        """operationId: stop_addresses_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/stop-addresses/", params=params or None)
        return PaginatedStopAddressList.model_validate(data)

    async def create(self, body: StopAddressRequest) -> StopAddress:
        """operationId: stop_addresses_create"""
        data = await self._client.post(
            "/api/stop-addresses/", json=body.model_dump(exclude_none=True)
        )
        return StopAddress.model_validate(data)

    async def retrieve(self, uuid: str) -> StopAddress:
        """operationId: stop_addresses_retrieve"""
        data = await self._client.get(f"/api/stop-addresses/{uuid}/")
        return StopAddress.model_validate(data)

    async def update(self, uuid: str, body: StopAddressRequest) -> StopAddress:
        """operationId: stop_addresses_update"""
        data = await self._client.put(
            f"/api/stop-addresses/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StopAddress.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedStopAddressRequest) -> StopAddress:
        """operationId: stop_addresses_partial_update"""
        data = await self._client.patch(
            f"/api/stop-addresses/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return StopAddress.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: stop_addresses_destroy"""
        await self._client.delete(f"/api/stop-addresses/{uuid}/")
