# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedTableList,
    PatchedTableWriteRequest,
    Table,
    TableRequest,
    TableWrite,
    TableWriteRequest,
)


class TablesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: tables"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
    ) -> PaginatedTableList:
        """operationId: tables_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        data = await self._client.get("/api/tables/", params=params or None)
        return PaginatedTableList.model_validate(data)

    async def create(self, body: TableWriteRequest) -> TableWrite:
        """operationId: tables_create"""
        data = await self._client.post("/api/tables/", json=body.model_dump(exclude_none=True))
        return TableWrite.model_validate(data)

    async def retrieve(self, uuid: str) -> Table:
        """operationId: tables_retrieve"""
        data = await self._client.get(f"/api/tables/{uuid}/")
        return Table.model_validate(data)

    async def update(self, uuid: str, body: TableWriteRequest) -> TableWrite:
        """operationId: tables_update"""
        data = await self._client.put(
            f"/api/tables/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return TableWrite.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedTableWriteRequest) -> TableWrite:
        """operationId: tables_partial_update"""
        data = await self._client.patch(
            f"/api/tables/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return TableWrite.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: tables_destroy"""
        await self._client.delete(f"/api/tables/{uuid}/")

    async def cancel_create(self, uuid: str, body: TableRequest) -> Table:
        """operationId: tables_cancel_create"""
        data = await self._client.post(
            f"/api/tables/{uuid}/cancel/", json=body.model_dump(exclude_none=True)
        )
        return Table.model_validate(data)

    async def close_create(self, uuid: str, body: TableRequest) -> Table:
        """operationId: tables_close_create"""
        data = await self._client.post(
            f"/api/tables/{uuid}/close/", json=body.model_dump(exclude_none=True)
        )
        return Table.model_validate(data)

    async def today_retrieve(self) -> Table:
        """operationId: tables_today_retrieve"""
        data = await self._client.get("/api/tables/today/")
        return Table.model_validate(data)
