# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    AvailableV2Report,
    GenerateTempReport,
    GenerateTempReportRequest,
    PaginatedTempReportList,
    TempReport,
)


class TempReportsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: temp-reports"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedTempReportList:
        """operationId: temp_reports_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/temp-reports/", params=params or None)
        return PaginatedTempReportList.model_validate(data)

    async def retrieve(self, uuid: str) -> TempReport:
        """operationId: temp_reports_retrieve"""
        data = await self._client.get(f"/api/temp-reports/{uuid}/")
        return TempReport.model_validate(data)

    async def download_retrieve(self, uuid: str) -> TempReport:
        """operationId: temp_reports_download_retrieve"""
        data = await self._client.get(f"/api/temp-reports/{uuid}/download/")
        return TempReport.model_validate(data)

    async def raw_retrieve(self, uuid: str) -> TempReport:
        """operationId: temp_reports_raw_retrieve"""
        data = await self._client.get(f"/api/temp-reports/{uuid}/raw/")
        return TempReport.model_validate(data)

    async def available_retrieve(self) -> AvailableV2Report:
        """operationId: temp_reports_available_retrieve"""
        data = await self._client.get("/api/temp-reports/available/")
        return AvailableV2Report.model_validate(data)

    async def start_pipeline_create(self, body: GenerateTempReportRequest) -> GenerateTempReport:
        """operationId: temp_reports_start_pipeline_create"""
        data = await self._client.post(
            "/api/temp-reports/start-pipeline/", json=body.model_dump(exclude_none=True)
        )
        return GenerateTempReport.model_validate(data)
