# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedTicketTemplateList,
    PatchedTicketTemplateRequest,
    TicketPreviewRequest,
    TicketRenderRequest,
    TicketTemplate,
    TicketTemplateRequest,
)


class TicketsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: tickets"""

    async def template_schema_retrieve(self) -> Any:
        """operationId: tickets_template_schema_retrieve"""
        data = await self._client.get("/api/tickets/template-schema/")
        return data

    async def templates_list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedTicketTemplateList:
        """operationId: tickets_templates_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/tickets/templates/", params=params or None)
        return PaginatedTicketTemplateList.model_validate(data)

    async def templates_create(self, body: TicketTemplateRequest) -> TicketTemplate:
        """operationId: tickets_templates_create"""
        data = await self._client.post(
            "/api/tickets/templates/", json=body.model_dump(exclude_none=True)
        )
        return TicketTemplate.model_validate(data)

    async def templates_retrieve(self, uuid: str) -> TicketTemplate:
        """operationId: tickets_templates_retrieve"""
        data = await self._client.get(f"/api/tickets/templates/{uuid}/")
        return TicketTemplate.model_validate(data)

    async def templates_partial_update(
        self,
        uuid: str,
        body: PatchedTicketTemplateRequest,
    ) -> TicketTemplate:
        """operationId: tickets_templates_partial_update"""
        data = await self._client.patch(
            f"/api/tickets/templates/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return TicketTemplate.model_validate(data)

    async def templates_destroy(self, uuid: str) -> None:
        """operationId: tickets_templates_destroy"""
        await self._client.delete(f"/api/tickets/templates/{uuid}/")

    async def templates_by_recipient_retrieve(self, recipient: str) -> TicketTemplate:
        """operationId: tickets_templates_by_recipient_retrieve"""
        data = await self._client.get(f"/api/tickets/templates/by-recipient/{recipient}/")
        return TicketTemplate.model_validate(data)

    async def templates_preview_create(self, body: TicketPreviewRequest) -> Any:
        """operationId: tickets_templates_preview_create"""
        data = await self._client.post(
            "/api/tickets/templates/preview/", json=body.model_dump(exclude_none=True)
        )
        return data

    async def templates_render_create(self, body: TicketRenderRequest) -> Any:
        """operationId: tickets_templates_render_create"""
        data = await self._client.post(
            "/api/tickets/templates/render/", json=body.model_dump(exclude_none=True)
        )
        return data
