# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedTrackingCodeList,
    PatchedTrackingCodeRequest,
    TrackingCode,
    TrackingCodeCreate,
    TrackingCodeCreateRequest,
    TrackingCodeRequest,
)


class TrackingCodesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: tracking-codes"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedTrackingCodeList:
        """operationId: tracking_codes_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/tracking-codes/", params=params or None)
        return PaginatedTrackingCodeList.model_validate(data)

    async def create(self, body: TrackingCodeCreateRequest) -> TrackingCodeCreate:
        """operationId: tracking_codes_create"""
        data = await self._client.post(
            "/api/tracking-codes/", json=body.model_dump(exclude_none=True)
        )
        return TrackingCodeCreate.model_validate(data)

    async def retrieve(self, uuid: str) -> TrackingCode:
        """operationId: tracking_codes_retrieve"""
        data = await self._client.get(f"/api/tracking-codes/{uuid}/")
        return TrackingCode.model_validate(data)

    async def update(self, uuid: str, body: TrackingCodeRequest) -> TrackingCode:
        """operationId: tracking_codes_update"""
        data = await self._client.put(
            f"/api/tracking-codes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return TrackingCode.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedTrackingCodeRequest) -> TrackingCode:
        """operationId: tracking_codes_partial_update"""
        data = await self._client.patch(
            f"/api/tracking-codes/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return TrackingCode.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: tracking_codes_destroy"""
        await self._client.delete(f"/api/tracking-codes/{uuid}/")
