# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints


class UnitsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: units"""

    async def retrieve(self) -> Any:
        """operationId: units_retrieve"""
        data = await self._client.get("/api/units/")
        return data
