# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints


class UntaggedEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: untagged"""

    async def root_retrieve(self) -> Any:
        """operationId: root_retrieve"""
        data = await self._client.get("/api/")
        return data
