# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedUserSerializerWithProfileList,
    PatchedUserSerializerWithProfileRequest,
    UserSerializerWithProfile,
    UserSerializerWithProfileRequest,
)


class UsersEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: users"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedUserSerializerWithProfileList:
        """operationId: users_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/users/", params=params or None)
        return PaginatedUserSerializerWithProfileList.model_validate(data)

    async def create(self, body: UserSerializerWithProfileRequest) -> UserSerializerWithProfile:
        """operationId: users_create"""
        data = await self._client.post("/api/users/", json=body.model_dump(exclude_none=True))
        return UserSerializerWithProfile.model_validate(data)

    async def retrieve(self, username: str) -> UserSerializerWithProfile:
        """operationId: users_retrieve"""
        data = await self._client.get(f"/api/users/{username}/")
        return UserSerializerWithProfile.model_validate(data)

    async def update(
        self, username: str, body: UserSerializerWithProfileRequest
    ) -> UserSerializerWithProfile:
        """operationId: users_update"""
        data = await self._client.put(
            f"/api/users/{username}/", json=body.model_dump(exclude_none=True)
        )
        return UserSerializerWithProfile.model_validate(data)

    async def partial_update(
        self,
        username: str,
        body: PatchedUserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: users_partial_update"""
        data = await self._client.patch(
            f"/api/users/{username}/", json=body.model_dump(exclude_none=True)
        )
        return UserSerializerWithProfile.model_validate(data)

    async def destroy(self, username: str) -> None:
        """operationId: users_destroy"""
        await self._client.delete(f"/api/users/{username}/")

    async def login_as_create(
        self,
        username: str,
        body: UserSerializerWithProfileRequest,
    ) -> UserSerializerWithProfile:
        """operationId: users_login_as_create"""
        data = await self._client.post(
            f"/api/users/{username}/login-as/", json=body.model_dump(exclude_none=True)
        )
        return UserSerializerWithProfile.model_validate(data)
