# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedVehicleList,
    PatchedVehicleRequest,
    Vehicle,
    VehicleRequest,
)


class VehiclesEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: vehicles"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedVehicleList:
        """operationId: vehicles_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/vehicles/", params=params or None)
        return PaginatedVehicleList.model_validate(data)

    async def create(self, body: VehicleRequest) -> Vehicle:
        """operationId: vehicles_create"""
        data = await self._client.post("/api/vehicles/", json=body.model_dump(exclude_none=True))
        return Vehicle.model_validate(data)

    async def retrieve(self, uuid: str) -> Vehicle:
        """operationId: vehicles_retrieve"""
        data = await self._client.get(f"/api/vehicles/{uuid}/")
        return Vehicle.model_validate(data)

    async def update(self, uuid: str, body: VehicleRequest) -> Vehicle:
        """operationId: vehicles_update"""
        data = await self._client.put(
            f"/api/vehicles/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Vehicle.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedVehicleRequest) -> Vehicle:
        """operationId: vehicles_partial_update"""
        data = await self._client.patch(
            f"/api/vehicles/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Vehicle.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: vehicles_destroy"""
        await self._client.delete(f"/api/vehicles/{uuid}/")
