# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedVendorList,
    PatchedVendorRequest,
    Vendor,
    VendorRequest,
)


class VendorsEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: vendors"""

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ordering: str | None = None,
        search: str | None = None,
    ) -> PaginatedVendorList:
        """operationId: vendors_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        if ordering is not None:
            params["ordering"] = ordering
        if search is not None:
            params["search"] = search
        data = await self._client.get("/api/vendors/", params=params or None)
        return PaginatedVendorList.model_validate(data)

    async def create(self, body: VendorRequest) -> Vendor:
        """operationId: vendors_create"""
        data = await self._client.post("/api/vendors/", json=body.model_dump(exclude_none=True))
        return Vendor.model_validate(data)

    async def retrieve(self, uuid: str) -> Vendor:
        """operationId: vendors_retrieve"""
        data = await self._client.get(f"/api/vendors/{uuid}/")
        return Vendor.model_validate(data)

    async def update(self, uuid: str, body: VendorRequest) -> Vendor:
        """operationId: vendors_update"""
        data = await self._client.put(
            f"/api/vendors/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Vendor.model_validate(data)

    async def partial_update(self, uuid: str, body: PatchedVendorRequest) -> Vendor:
        """operationId: vendors_partial_update"""
        data = await self._client.patch(
            f"/api/vendors/{uuid}/", json=body.model_dump(exclude_none=True)
        )
        return Vendor.model_validate(data)

    async def destroy(self, uuid: str) -> None:
        """operationId: vendors_destroy"""
        await self._client.delete(f"/api/vendors/{uuid}/")
