# generated by scripts/generate_endpoints.py
# DO NOT EDIT — re-run `make generate-endpoints` to update

from __future__ import annotations

from typing import Any

from cpk_sdk.client.endpoints import BaseEndpoints
from cpk_sdk.client.models.generated import (
    PaginatedWhatsappNumberList,
    WhatsappNumber,
    WhatsappNumberRequest,
)


class WhatsappNumbersEndpoints(BaseEndpoints):
    """Auto-generated endpoints for tag: whatsapp-numbers"""

    async def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedWhatsappNumberList:
        """operationId: whatsapp_numbers_list"""
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._client.get("/api/whatsapp-numbers/", params=params or None)
        return PaginatedWhatsappNumberList.model_validate(data)

    async def create(self, body: WhatsappNumberRequest) -> WhatsappNumber:
        """operationId: whatsapp_numbers_create"""
        data = await self._client.post(
            "/api/whatsapp-numbers/", json=body.model_dump(exclude_none=True)
        )
        return WhatsappNumber.model_validate(data)

    async def retrieve(self, uuid: str) -> WhatsappNumber:
        """operationId: whatsapp_numbers_retrieve"""
        data = await self._client.get(f"/api/whatsapp-numbers/{uuid}/")
        return WhatsappNumber.model_validate(data)
